
import COMMON from '../utils/common.json'
import { getRandomEmail } from './helper'

export const constants = {
    backupParentData: {
        firstName: "Emily",
        lastName: "Thompson",
        email: "Emily@gmail.com",
        phone: "+12342432343",
        addressLine1: "18 East 34th Street",
        addressLine2: "Suite 1203",
        city: "Alaska",
        state: "Alaska",
        zipCode: "10016",
        country: "United States"
    },
    primaryPetGuardianData: {
        firstName: "Oliver",
        lastName: "Bennett",
        email: "oliver.bennett@gmail.com",
        phone: "+13475551234",
        addressLine1: "1111 Brickell Avenue",
        addressLine2: "Apt 7A",
        city: "Miami",
        state: "Florida",
        zipCode: "33131",
        country: "United States"
    },
    spousePrimaryPetGuardianData: {
        firstName: "Isabella",
        lastName: "Carter",
        email: "isabella.carter@gmail.com",
        phone: "+14155559876",
        addressLine1: "225 Lincoln Avenue",
        addressLine2: "Unit 12B",
        city: "Denver",
        state: "Colorado",
        zipCode: "80203",
        country: "United States"
    },
    primaryParentData: {
        firstName: "James",
        lastName: "Harrington",
        email: "James@gmail.com",
        phone: "+12342432343",
        addressLine1: "245 West 72nd Street",
        addressLine2: "Apartment 5B",
        city: "Florida",
        state: "Florida",
        zipCode: "10023",
        country: "United States"
    },
    itemData: {
        name: "Antique Vase",
        description: "A vintage Chinese porcelain vase from the 19th century",
        estimatedValue: "12000"
    },
    backupExecutorData: {
        firstName: "Sarah",
        lastName: "Thompson",
        email: "sarah.thompson@gmail.com",
        phone: "+12345678902",
        addressLine1: "425 Park Avenue",
        addressLine2: "Apt 8B",
        city: "Birmingham",
        state: "Alabama",
        zipCode: "35203",
        country: "United States"
    },
    executorData: {
        firstName: "Michael",
        lastName: "Anderson",
        email: "michael.anderson@gmail.com",
        phone: "+12345678901",
        addressLine1: "350 Madison Avenue",
        addressLine2: "Suite 1200",
        city: "Alabama",
        state: "Alabama",
        zipCode: "10017",
        country: "United States"
    },
    healthCareAgentData: {
        firstName: "Sarah",
        lastName: "Williams",
        email: "sarah.williams@gmail.com",
        phone: "+12398765432",
        addressLine1: "500 Park Avenue",
        addressLine2: "Suite 1500",
        city: "Florida",
        state: "Florida",
        zipCode: "10022",
        country: "United States"
    },
    backupHealthCareAgentData: {
        firstName: "Daniel",
        lastName: "Roberts",
        email: "daniel.roberts@gmail.com",
        phone: "+12398765433",
        addressLine1: "275 Lexington Avenue",
        addressLine2: "Floor 10",
        city: "Florida",
        state: "Florida",
        zipCode: "10016",
        country: "United States"
    },
    financialAgentData: {
        firstName: "David",
        lastName: "Miller",
        email: "david.miller@gmail.com",
        phone: "+12345678902",
        addressLine1: "600 Lexington Avenue",
        addressLine2: "Suite 2100",
        city: "Alaska",
        state: "Alaska",
        zipCode: "10022",
        country: "United States"
    },
    successorData: {
        firstName: "Michael",
        lastName: "Johnson",
        email: "michael.johnson@gmail.com",
        phone: "+12345678903",
        addressLine1: "123 Maple Avenue",
        addressLine2: "Apt 5B",
        city: "Florida",
        state: "Florida",
        zipCode: "10001",
        country: "United States"
    },
    monitorData: {
        firstName: "Laura",
        lastName: "Wilson",
        email: "laura.wilson@gmail.com",
        phone: "+12345678902",
        addressLine1: "500 Tech Park Drive",
        addressLine2: "Building 3, Suite 210",
        city: "Alabama",
        state: "Alabama",
        zipCode: "10018",
        country: "United States"
    },
    backupAgentData: {
        firstName: "Olivia",
        lastName: "Johnson",
        email: "olivia.johnson@gmail.com",
        phone: "+12345678903",
        addressLine1: "700 Madison Avenue",
        addressLine2: "Suite 3100",
        city: "Florida",
        state: "Florida",
        zipCode: "10022",
        country: "United States"
    },
    backupPetGuardianData: {
        firstName: "Sophia",
        lastName: "Williams",
        email: "sophia.williams@gmail.com",
        phone: "+16465559876",
        addressLine1: "42 East 29th Street",
        addressLine2: "Floor 3",
        city: "Alaska",
        state: "Alaska",
        zipCode: "10016",
        country: "United States"
    },
    spouseBackupPetGuardianData: {
        firstName: "Madeline",
        lastName: "Hawkins",
        email: "madeline.hawkins@gmail.com",
        phone: "+15705551234",
        addressLine1: "88 Cherry Blossom Lane",
        addressLine2: "Apt 5C",
        city: "Seattle",
        state: "Washington",
        zipCode: "98101",
        country: "United States"
    },
    petPropertyData: {
        addressLine1: "123 Maple Avenue",
        addressLine2: "Apt 4C",
        city: "Brooklyn",
        state: "Alaska",
        zipCode: "11215",
        country: "United States",
        approximateValue: "150000",
    },
    secondaryPetPropertyData: {
        addressLine1: "600 West 7th Avenue",
        addressLine2: "Apt 4C",
        city: "Anchorage",
        state: "Alaska",
        zipCode: "99501",
        country: "United States",
        approximateValue: "5000",
    },
    newPassword: COMMON.newPassword,
    password: COMMON.password,
    fullName: 'Ambreen Test',
    congratsMessage: "Congratulations, ",
    enterState: 'Alab',
    selectStateFromDropdown: 'Alabama',
    singleRelationshipStatus: 'Single',
    marriedStatus: "Married",
    petName: "Tony",
    addressLine1: "123 Main St",
    resetPasswordTxt: "Reset password",
    addressLine2: "Apt 4B",
    city: "New York",
    zipcode: "10001",
    enterCountery: "United",
    selectCountryFromDropdown: "United States",
    birthdayDate: "01/03/2006",
    spouseBirthdayDate: "01/10/2000",
    childName: "Waheed",
    caringPersonAmount: "300",
    guardianType: "Primary",
    valueOfAllAsset: "Up to $50k",
    radioButtonChecking: "Checking",
    propertyPersonName: "John",
    financialInstitution: "Chase Bank",
    approximateAccountValue: "25000",
    policyCarrier: "MetLife Insurance",
    policyType: "Term Life",
    policyValue: "50000",
    policyHolderName: "John Doe",
    businessName: "Doe Enterprises",
    businessType: "Solo Proprietorship",
    businessOwnershipValue: "75000",
    legacyContactFullname: "Edison Thomson",
    iName: "Emily Thomson",
    iEmail: "emily.thomson@gmail.com",
    legacyContactEmail: "edison.thomson@gmail.com",
    headingFirstNameTxt: "First, what's your name?",
    agetActTogetherOrIndep: "Should your agents act together or independently?",
    leaveMedicalCarforAgentTxt: "Do you want to leave medical care instructions for your agent?",
    anyLimitForHealthTxt: "Any limits for your health care agent?",
    wantDonateOrganTxt: "Do you want to donate your organs?",
    wantNameConservatorForEstate: "Do you want to name a conservator for your estate?",
    nominateBackupConservatorEstate: "Would you like to nominate a backup estate conservator?",
    screenOfFinancialAgentTxt: "Who should handle your finances if you can't?",
    wantRequireConservatorPostBond: "Do you want to require your conservator to post a bond?",
    whatTypeDecisionsAthorityToAgent: "What type of decisions can your Financial Agent make for you?",
    wouldLikeAddBackupRuleTxt: "Would you like to add backup rules just in case?",
    shouldAgentGiveGiftsTxt: "Should your agent be able to give gifts over $5,000?",
    leaveOutGiftingIntentionaly: "Do you want to leave out the gifting option intentionally?",
    leaveAnySpecialInstructions: "Would you like to leave any special instructions?",
    pwrAtteroneyExpire: "Do you want your Power of Attorney to expire on a set date or event?",
    specialInstruction: "Records of all transactions should be kept and shared when required.",
    powerAtteroneyOnSetDate: "This Power of Attorney should automatically end on the specified date or upon the occurrence of the chosen event. After this point, the appointed authority will no longer have permission to act on my behalf, and all responsibilities granted under this Power of Attorney will cease.",
    specificRestriction: "Restrictions are rules or conditions put in place to set clear boundaries and limits on actions or behavior.",
    backupRuleTxt: "If the primary guardian is unable to take responsibility, the children should be cared for by a trusted family member or close friend. This person should ensure the children’s safety, continue their education and routines, and act in their best interests until a permanent arrangement is made.",
    modifyStandardPowerAttorneyTxt: "Would you like to make any modifications to the standard Power of Attorney?",
    overviewTxt: "Overview",
    summaryTxt: "Summary",
    thomasEdison: "Thomas Edison",
    assetsTxt: "Assets",
    nextStepCardsTxt: "NEXT STEPS",
    welcomeAmbreenTxt: "Welcome, Ambreen!",
    whatStatYouLivedTxt: "what state do you live in?",
    successorAgenScreenDisplayed: "Who would you like to name as backup agents if your primary agent is unable to serve?",
    previousPowerofAttorneyDocumentTxt: "Do you want to revoke any previous Power of Attorney documents?",
    healthCareProxyExpiryMessage: "I would like my Health Care Proxy to remain in effect until my 80th birthday, after which it should expire automatically.",
    wantWhenHealthProxyNoLongerEffectTxt: "Do you want to choose a date or event when your Health Care Proxy will no longer be in effect?",
    wouldLikeGivePermissionViewMedicalRecordsTxt: "Would you like to give any other people permission to view your medical records?",
    cremondyRequest: "I would like the song ‘Imagine’ by John Lennon to be played. Please invite my close friends and family, especially my cousin Sarah and best friend Daniel. I would also appreciate having a small moment of reflection with everyone sharing a fond memory.",
    resetPasswordTxt: "Reset password",
    wantNameBackupFinancialAgenTxt: "Would you like to name a backup financial agent?",
    wouldLikeBackRuleForBackAgetntxt: "Would you like to add backup rules for the backup agent to become the main agent?",
    wouldCreatPlanForPartnerTxt: "Would you also like to create a plan for your partner?",
    bothOfUsTxt: "For both of us",
    guardianNominationTxt: "Do you want to name a guardian for your children?",
    downloadHipaaDocumentXpath: "//div[div[h3[normalize-space()='HIPAA']]]/following-sibling::div/a[normalize-space()='Download']",

}