export const generalPage = {
    homeHeader: 'nav',
    homeBody: 'main',
    homeFooter: 'footer', 
    linkedInLable: 'LinkedIn', 
    facebookLable: 'Facebook', 
    instagramLable: 'Instagram',
    bannerHeadingEstatePlanning: 'Estate Planning Made Simple', 
    createTrustThatWorksTxt: "Create a Trust That Works for You",
    createYourWillTxt: "Create Your Will In Minutes",
    estatePlaningExpTxt: "Estate Planning Explained",
    buildYourBusinessTxt: "Build Your Business in a",
    modernEstatePlaningSimplePricTxt: "Modern Estate Planning, Simple Pricing",
    willTxt: 'Will',
    pricingTxt: "Pricing",
    trustTxt: 'Trust',
    learnTxt: 'Learn',
    professionalsTxt: 'Professionals',
    logInTxt: 'Log In',
    startTodayTxt: 'Start Today',
    privacyPolicyTxt: "Privacy Policy",
    termsServiceTxt: "Terms of Service",
    pricingURL: "plans-and-pricing",
    trustPageURL: 'trust-package',
    willPageURL: 'will-package',
    learnPageURL: 'estate-planning-guide',
    professionalsURL: "professionals",
    professionalsPageURL:'financial-advisors',
    privacyPolicyPageURL: 'privacy-policy',
    termsServicesPageURL: 'terms-of-service',
    welcomeFastWillURL: "will-creation",
    loginPageURL: 'login', 
    linkedInPage: 'fastwill', 
    fastWillTxt: "FastWill",
    selectDateTxt: "Select Date",
    pleaseLoginToAccountTxt: "Please log in to your account",
    welcomeFastwillTxt: 'Welcome to FastWill', 
    headingFirstNameTxt: "First, what's your name?", 
    namePlaceholderTxt: 'Enter your name',
    continueTxt: "Continue", 
    logoutTxt: 'Logout', 
    statPlaceHolderText: 'Search for your state...',
    avoidProbateYes: "Yes, I'd like my estate to avoid probate.",
    avoidProbateNo: "No, I'm ok with my estate going through probate.",
    paymentSuccessDeedTransferTxt: "Payment successful! Processing your deed transfer order...",
    deedTransferConfirmedTxt: "Your Deed Transfer Is Confirmed!",
    preparingDeedCapTxt: "PREPARING DEED",
    continueWithEmailTxt: 'Continue with email', 
    createAccountTxt: 'Create Account',
    selectThisBundleTxt: 'Select This Bundle',
    selectWillBundleTxt: "Select Will Bundle",
    selectWillOnlyTxt: "Select Will Only",
    selectTrustOnly: "Select Trust Only",
    paymentTxt: 'Payment',     
    gotoDashboard: "Go to Dashboard",
    dashboard: "Dashboard",
    documentsTxt: "Documents",
    myDocumentsCapTxt: "MY DOCUMENTS",
    legacyContactsTxt: "Legacy Contacts",
    addTrustedLegacyContactToYourAccountTxt: "Add a trusted Legacy Contact to your account to make sure someone you trust can access your documents in an emergency.",
    backToOverview: "Back to Overview",
    financialInstitutionLabel: "Financial institution",
    noTxt: "No",
    exitTxt: "Exit",
    addAContactTxt: "Add a Contact",
    addAccountTxt: "Add Account",
    petsNameLabel: "Pet's Name",
    amountLabel: "Amount",
    fullNameLabel: "Full name",
    termsCheckboxId: '#terms-checkbox',
    confirmAndPayBtnTxt: 'Confirm & Pay',
    thanksforPurchaseTxt: "Thank you for your purchase!",
    postalCodePlaceHolder: 'M5T 1T4',
    cvcPlacholder: 'CVC',
    expireyPlaceholder: 'MM / YY',
    cardNumberPlaceholder: "1234 1234 1234 1234",
    whatYourAddressTxt: "What is your address?",
    whatisYourbirthdayTxt: "Great! Now, what is your birthday?",
    doYouHaveChildTxt: "Do you have children?",
    haveChildrenTxt: "have children?",
    guardianNominationTxt: "Do you want to name a guardian for your children?",
    whatIsSpousenameTxt: "What's your spouse's name?",
    whoLookAfterYourChilderenTxt: "Who would you like to look after",
    wouldYouLikeNameConservatorChild: "Would you like to name a conservator for your children?",
    whoWouldYouLiketoNameAsConservator: "Who would you like to name as the conservator?",
    futureAdoptionChildrenWillTxt: "Would you like to include any future or adopted children in your Will?",
    testLivingTrustTxt: "Perfect. Would you like the Trust to be called the “Test Living Trust”?",
    whenWouldYouBeginTrust: "When would you like your Trust to begin?",
    wouldYouMainPersonToManageTrustTxt: "Will you be the main person managing this Trust while you're alive?",
    areYouAsGrantorTxt: "Are you, as a Grantor, also the lifetime beneficiary?",
    wholWillLifetimeBeneficiaryTxt: "Who will be the lifetime beneficiary of the Trust?",
    whoShouldTrusteeIncapacitatedTxt: "Who should take over if the Trustee is incapacitated?",
    whoWouldTakeOverPassAwayTxt: "Who should take over if the Trustee passes away?",
    doYouHavePetTxt: "Do you have any pets?",
    doYouWantChoosePetGuardianTxt: "Do you want to choose guardians for any of your pets?", 
    listOfPetsDescTxt: "Okay, let's list each of your pets you'd like to nominate guardians for:",
    petGuardianAssignmentTxt: "Who would you like to look after ",
    setAsideMoenyToCaringPersonHelp:"Would you like to set aside some money to help the person caring for your pets?",
    beneficairyReceiveInheritanceTxt: "Should your beneficiaries receive their inheritance right away?",
    wantExludeFromWill: "Do you want to exclude anyone from your Will?",
    shouldExecutorRequiredBond:"Should the executor be required to get a bond?",
    wantBackupExecutor: "Do you want to name a backup executor?",
    whoWillbeExecutorTxt: "Who will be your executor?",
    whoWillbeBackupExecutorTxt: "Who will be your backup executor?",
    wouldYouLikeProtectWillFromPotentialDesputeTxt:"Would you like to protect your Will from potential disputes?",
    wantNameBackupHealthAgentTxt: "Do you want to name a backup healthcare agent?",
    whoWillBackupAgentTxt: "Who will be your backup healthcare agent?",
    wantToMonitorTxt:"Do you want to name a monitor?",
    whoWouldLikeNameasMonitorTxt: "Who would you like to name as the Monitor?",
    wantNameConservatorEstateTxt: "Do you want to name a conservator for your estate?",
    wantNominateGuardianForSelfTxt: "Do you want to nominate a guardian for yourself?",
    whoWillMakeMedicalDecision: "Who will make medical decisions for you if you can't?",
    haveSpecialRequestforCremony: "Do you have any special requests or instructions for your ceremony?",
    willSpousebeMainManaingTrustTxt: "Will you and your spouse be the main people managing this Trust while you're alive?",
    questionSymbol: "?",
    resetPasswordTxt: "Reset password",
    acceptCookiesTxt: "Accept Cookies", 
    notary9To5AmTxt: "Notary sessions can only be created between 9 AM and 5 PM in your timezone.",
    notaryCreateSessionTxt: "Create Notary Session",
    notaryCreatedSuccessMessage: "Notarization session created successfully!",
    joinSessionNowTxt: "Join Session Now",
    addressLine1Placeholder: "123 Main St",
    addressLine2Placeholder: "Apt 4B",
    cityPlaceholder: "San Francisco",
    zipCodePlaceholder: "94102",
    countryPlaceholder: "United States",
    selecteDatePlaceholder: "Select date", 
    childNamePlaceholder: "e.g. Charles Edison", 
    yesTxt: "Yes",
    addChildTxt: "Add a Child",
    meTxt: "Me",
    selectBirthdayFieldPlaceholder: "Select date of birth",
    saveTxt: "Save", 
    forgetPasswordTxt: "Forgot password?",
    newYorkTxt: "New York",
    addContactTxt: "Add Contact",
    addConservator: "Add a Conservator",
    addPetTxt: "Add a Pet",
    addAddress: "Add Address",
    addPropertyTxt: "Add Property",
    addAccountTxt: 'Add Account',
    businessTypePlaceHolderTxt: "e.g., Solo Proprietorship",
    privacyTypePlaceHolderTxt: 'e.g., Term Life',
    calculatingTxt: "Calculating...",
    totalTxt: 'Total',
    totalNotarizationTxt: 'Notarization Total',
    notarizationTxt: "Notarization",
    howItWorksTxt: "How it works",
    securePaymentToDeedTransferTxt: "Secure your payment to begin your deed transfer",
    getStartedTxt: "Get Started",
    deedTransferCalculationTxt: "Deed Transfer Calculation",
    addressTxt: "Address",
    whatYoullNeedTxt: "What You'll Need",
    previewTxt: "Preview",
    downloadTxt: "Download",
    downloadAllTxt: "Download All",
    manageSharingAccessTxt: "Manage Sharing Access",
    saveChangesTxt: "Save Changes",
    cancelTxt: "Cancel",
    magicAddAnnualSubscTxt: "Magic Add Annual Subscription",
    subscAllowEditDocumentTxt: "Subscription allows you to edit your documents anytime.",
    succfullyUpdateAccessForTxt: "Successfully updated access for",
    getStartedNotarizingTxt: "Get Started Notarizating",
    lastWillAndTestament: "Last Will & Testament",
    advanceCareDirectiveTxt: "Advance Care Directive",
    powerOfAttorneyTxt: "Power of Attorney",
    pourOverWillTxt: "Pour-Over Will",
    revocableLivingTrustTxt: "Revocable Living Trust",
    scheduleOfAssetsTxt: "Schedule of Assets",
    fundingInstructionTxt: "Funding Instructions",
    certificationOfTrustTxt: "Certification of Trust",
    wouldLiktoPurchase5Each: "I'd like to purchase witnesses – $5 each",
    twoProfessionalWitnessesTxt: "2 professional witnesses",
    estatePlanDocumenTxt: "Estate Plan Document(s)",
    notaryWitnessesTxt: "Notary Witnesses",
    witnessSpouseEmailPlaceholder: "ex: jane@example.com",
    deedTranserTotalTxt: "Deed Transfer Total",
    subtotalTxt: "Subtotal",
    spouseInputPlaceHolder: "e.g. Thomas Edison",
    thomasEdisonName: "Thomas Edison",
    radioButtonChecking: "Checking",
    valueOfAllAsset: "Up to $50k",
    welcomeAmbreenTxt: "Welcome, Ambreen!",
     overviewTxt: "Overview",
    summaryTxt: "Summary",
    nextStepCardsTxt: "NEXT STEPS",
    notarizeNowTxt: "Notarize Now",
    addNowTxt: "Add Now",
    sendInviteTxt: "Send Invite",
    nameLabel: "Name",
    ambreenTestName: "Ambreen Test",
    ambreenTest123Name: "Ambreen Test 124",
    oliverBennettName: "Oliver Bennett",
    timeToMakeYourPlanOfficialTxt: "It's time to make your plan official in Alabama!",
    legacyContactFullnameLabel: "Enter your contact's full name",
    legacyContactEmailLabel: "Enter your contact's email",
    invitationSentSuccessTxt: "Invitation sent successfully!",
    updatedDocumentAccessTxt: "Successfully updated document access for",
    anyLimitForHealthTxt: "Any limits for your health care agent?",
    wantDonateOrganTxt: "Do you want to donate your organs?",
    previousPowerofAttorneyDocumentTxt: "Do you want to revoke any previous Power of Attorney documents?",
    screenOfFinancialAgentTxt: "Who should handle your finances if you can't?",
    wantNameBackupFinancialAgenTxt: "Would you like to name a backup financial agent?",
    successorAgenScreenDisplayed: "Who would you like to name as backup agents if your primary agent is unable to serve?",
    wouldLikeBackRuleForBackAgetntxt: "Would you like to add backup rules for the backup agent to become the main agent?",
    whatTypeDecisionsAthorityToAgent: "What type of decisions can your Financial Agent make for you?",
    wantWhenHealthProxyNoLongerEffectTxt: "Do you want to choose a date or event when your Health Care Proxy will no longer be in effect?",
    modifyStandardPowerAttorneyTxt: "Would you like to make any modifications to the standard Power of Attorney?",
    wouldLikeGivePermissionViewMedicalRecordsTxt: "Would you like to give any other people permission to view your medical records?",
    shouldAgentGiveGiftsTxt: "Should your agent be able to give gifts over $5,000?",
    leaveAnySpecialInstructions: "Would you like to leave any special instructions?",
    pwrAtteroneyExpire: "Do you want your Power of Attorney to expire on a set date or event?",
    leaveOutGiftingIntentionaly: "Do you want to leave out the gifting option intentionally?",
    leaveMedicalCarforAgentTxt: "Do you want to leave medical care instructions for your agent?",
    whenWas:`When was `,
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    phone: "Phone",
    numberOfDaysLabel: "Number of Days",
    myDecendentsTxt: "My Descendants",
    perStirpesTxt: "Per Stirpes",
    addressLine1: "Address line 1",
    addressLine2: "Address line 2",
    addressLine2Property: "Address line 2 (apt, floor, ste, etc)",
    approximateValue: "Approximate value (optional)", 
    approxmateAccountValue: "Approximate account value (optional)",
    estimateValueLabel: "Estimated value (optional)",
    nameOfPersonOrOrganizationLabel: "Name of the person or organization",
    cremationTxt: "Cremation",
    memorialServiceTxt: "Memorial Service",
    myRequestLabel: "My request",
    addHealthCareAgentTxt: "Add a Healthcare Agent",
    organsNeededEyesTissuesTxt: "Any needed organs, eyes and/or tissues",
    authorizedPersonTxt: "Authorized Person",
    yesIwouldLikeToChooseTxt: "Yes, I'd like to choose",
    thisProxyShallExpireLabel: "This proxy shall expire (specific date or conditions)",
    addFinancialAgentTxt: "Add a Financial Agent",
    addBackupAgentTxt: "Add Backup Agent",
    describeBackupRuleLabel: "Describe your backup rules",
    realPropertyTxt: "Real Property",
    taxesTxt: "Taxes",
    hipaaAuthorizationTxt: "HIPAA Authorization",
    anySpecificRestrictionLabel: "Any specific restrictions?",
    yourSpecialInstructionsLabel: "Your special instructions",
    provideEvenOrDateLabel: "Provide event or date",
    guardianTxt: "Guardian",
    childrenTxt: "Children",
    addPolicyTxt: "Add Policy",
    policyCarrierTxt: "Policy carrier",
    valuePolicyLabel: "Value of policy (optional)",
    addIntrestTxt: "Add Interest",
    businessNameLabel: "Business name",
    valueOfOwnershipLabel: "Value of ownership (optional)",
    addItemTxt: "Add Item",
    itemNameLabel: "Item name",
    briefDescriptionLabel: "Brief description",
    inputTxt: "input",
    city: "City",
    state: "State",
    countyTxt: "County",
    ownerTxt: "Owner",
    zipCode: "Zip Code",
    zipPostalCode: "Zip/Postal code",
    country: "Country",
    assetTxt: "Assets",
    editAssetsTxt: "Edit Assets",
    otherTxt: "Other",
    businessesTxt: "Businesses",
    recordingFeesTxt: "Recording Fees",
    summaryServiceTxt: "Summary Service",
    brickellAvenueTxt: "1111 Brickell Avenue",
    metLifeInsuranceTxt: "MetLife Insurance",
    arrangementsTxt: "Arrangements",
    michealAndersonName: "Michael Anderson",
    memorialServicesTxt: "memorial-service",
    healthCareTxt: "Healthcare",
    sarahWilliamName: "Sarah Williams",
    yesAnyTxt: "Yes - Any",
    financialsTxt: "Financials",
    financialAccountsTxt: "Financial Accounts",
    propertiesTxt: "Properties",
    davidMillerName: "David Miller",
    manageAccessTxt: "Manage Access",
    editTxt: "Edit",
    confirmTxt: "Confirm",
    doneTxt: "Done",
    hipaaCapTxt: "HIPAA",
    upgradeGiftTxt: "Upgrade Gift",
    referAFriendTxt: "Refer a friend",
    gift20PercentOffToYourFriendTxt: "Gift 20% Off to Your Loved Ones",
    enterLoveoneNameLabel: "Enter your loved one's first name",
    enterLoveOneEmailLabel: "Enter your loved one's email",
    settingsTxt: "Settings",
    updateProfileTxt: "Update Profile",
    deedTranserTxt: "Deed Transfer",
    profileUpdateSuccessTxt: `Profile updated successfully!`,
    currentPasswordLabel: "Current Password",
    newPasswordLabel: "New Password",
    confirmNewPassLabel: "Confirm New Password",
    updatePasswordTxt: "Update Password",
    passUpdateSuccessTxt: `Password updated successfully!`,
    sharePlanWithSomeoneYouTrustTxt: "Share Your Plan With Someone You Trust",
    accessRemovedSuccessTxt: "Access removed successfully.",
    addTrustedLegacyContactaccountTxt: "Add a trusted Legacy Contact to your account to make sure",
    shareMyPlanTxt: "Share My Plan",
    contactNameTxt: "Contact Name",
    emailAddressTxt: "Email Address",
    addTxt: "Add",
    sharePlanTxt: "Share Plan",
    invitationSentTxt: "Invitations Sent!",
    updateProfileInfoToManageTxt: `Update your profile information and manage your account settings.`,
    parentRatioBtnTxt: (name) => `${name} and Me`,
    youReferralInviteSentToEmailTxt: (email)=> `Your referral invitation has been sent to ${email}.`,

    /** ids path */
    contactNameId: "#contactName",
    contactEmailId: "#deliverTo",
    emailId: '#email', 
    passwordId: '#password', 
    accountPasswordId: "#account-password",
    confirmPasswordId: "#password_confirmation",

    /** xpaths */
    xPathProfile: 'a[aria-label="Settings"]+div>button', 
    xpathAccountDropdown: 'a[aria-label="Settings"]+div>div', 
    checkValueForLabelXpath: 'xpath=following-sibling::*[1]',
    datePickerYearXpath: "//button[contains(@id,'datepicker_') and contains(@id,'_year_btn')]",
    datePickerMonthXpath: "//button[contains(@id,'datepicker_') and contains(@id,'_month_btn')]",
    xpathAddPrimaryGuardianButton: "//span[normalize-space()='Primary Guardian']/following-sibling::button",
    xpathBackupGuardianButton: "//span[normalize-space()='Backup Guardian']/following-sibling::button",
    xpathAddContactPrimaryGuardianButton: "(//h2[normalize-space()='Add a Contact']/following-sibling::div/button)[1]",
    xpathAddContactBackupGuardianButton: "(//h2[normalize-space()='Add a Contact']/following-sibling::div/button)[2]",
    modelCrossIcon: "//a[contains(@href, 'estate-checklist')]/following-sibling::button[img[@alt='Close']]",
    assetsTab: "//button[normalize-space()= 'Summary']/following-sibling::button[normalize-space()='Assets']",
    previewDocumentModelCloseIco: "//a[contains(@href, 'download/user')]/following-sibling::button[img[@alt='Close']]",
    basicXPath: "(//span[normalize-space()='Basic'])[2]",
    closeIcon: "(//div[a[contains(@href, 'dashboard/user')]])[1]/following-sibling::div/button",
    closeInviteModel: "//div[h2[contains(text(), 'Refer a friend')]]/following-sibling::button",
    manageAccessHipaXPath: "//div[div[h3[normalize-space()='HIPAA']]]/following-sibling::div/button[normalize-space()='Manage Access']",
    downloadHipaaDocumentXpath: "//div[div[h3[normalize-space()='HIPAA']]]/following-sibling::div/a[normalize-space()='Download']",
    removeAccessModelBtnXpath: "//div[h2[normalize-space()='Remove Legacy Contact']]/following-sibling::div/button[normalize-space()='Remove Access']",
    feeItemsXpath: "(//div[h3[normalize-space()='Recording Fees']/following-sibling::div])/div",
    totalFeeAmountXpath: "xpath=//span[normalize-space()='Total Recording Fees']/following::span[2]",
    deedTransferNotFeeXpath: "//span[normalize-space()='Amount']/following-sibling::span", 
    recordingFeeItemsCountXpath: "xpath=./div",
    recordingFeeRowXpath: "(//span[normalize-space()='Recording Fees'])/following-sibling::div",
    totalPriceXpath:"(//div[span[normalize-space()='Total']])[2]/following-sibling::span",
    propertyAmountXpath: "//div[div[div[div[div[contains(text(), 'Property Address')]]]]]//div[starts-with(normalize-space(text()), '$')]",
    sideDeedTransferXPath: "//aside[contains(@class, 'lg:block')]/nav/div/ul/li/a[./span[normalize-space()='Deed Transfer']]",
    dropdownXpath: '//div[@x-show="open" and not(contains(@style, "display=none"))]',
    byLableInputXpath: 'xpath=following-sibling::div//input[not(contains(@type, "hidden"))]',
    inputTxtByLabelXpath: 'xpath=following-sibling::div//input',
    addPropertyBtnXpath: "//div[div[h2[normalize-space()='Add a property' ]]]//button[normalize-space()='Add Property']",
    textAreaXpath: 'xpath=following-sibling::textarea',
    recordingFeeRowPriceItemXpath:(index)=> `(//span[normalize-space()='Recording Fees'])[${index}]/following-sibling::div/span[last()]`,
    recordingFeeItemXpath:(index) => `(//div[h3[normalize-space()='Recording Fees']/following-sibling::div])[${index}]/div/div[1]/div/div[contains(@class,'items-end')]/span[2]`,
    amountByLabelXpath: (label) => `(//span[normalize-space()='${label}'])[2]/following-sibling::span`,
    selectStateFromDropdown:(state) => `xpath=.//div[span[normalize-space()="${state}"]]`,
    valueByDivLabelXpath:(label) => `//div[normalize-space()='${label}']/following-sibling::div`, 
    documentTitleXpath: (title) => `//div[div[div[h3[normalize-space()='${title}']]]]`, 
    sideBarLinkXpath: (title) => `//aside[contains(@class, 'lg:block')]/nav/div/ul/li/a[./span[normalize-space()='${title}']]`,
    selectContactEmailXpath: (email) => `//div[./button[normalize-space()='Save Changes']]/preceding-sibling::div/div/label/div[./div[text()='${email}']]`,
    manageAccessBtnUsingEmailXpath: (email) => `//div[div[span[normalize-space()='${email}']]]/following-sibling::div/button[normalize-space()='Manage Access']`,
    removeAccessForContactsUsingEmailXpath: (email) => `//div[div[span[normalize-space()='${email}']]]/following-sibling::div/button[normalize-space()='Remove Access']`, 
    tabsUsingBaiscTabXpath: (text) => `(//span[normalize-space()='Basic'])[2]/following::span[normalize-space()='${text}']`,
    selectContactXpath: (name) => `(//div[div[span[normalize-space()='${name}']]]/following-sibling::div/button)`
}

export function getLocator(value) {

    switch (value) {
        case 'Alabama':
            return generalPage.statPlaceHolderText;
        case 'Florida':
            return generalPage.statPlaceHolderText;
        case 'New York':
            return generalPage.statPlaceHolderText;
        case 'Colorado':
            return generalPage.statPlaceHolderText;
        case 'Washington':
            return generalPage.statPlaceHolderText;
        case 'United States':
            return generalPage.countryPlaceholder;
        case 'Alaska':
            return generalPage.statPlaceHolderText;
        case 'Solo Proprietorship':
            return generalPage.businessTypePlaceHolderTxt;
        case 'Term Life':
            return generalPage.privacyTypePlaceHolderTxt;
        default:
            throw new Error(`Locator for "${value}" not defined`);
    }
}
