export const generalPage = {
    homeHeader: 'nav',
    homeBody: 'main',
    homeFooter: 'footer',
    linkedInLable: 'LinkedIn',
    facebookLable: 'Facebook',
    instagramLable: 'Instagram',
    bannerHeadingEstatePlanning: 'Estate Planning Made Simple',
    bannerDescEveryTxtthingneedSecureFutureTxt: "Everything you need to secure your future, right from home.",
    whichPlanFitsYourNeedsTxt: "Which Plan Fits Your Needs?",
    whenTrustMakesSenseTxt: "When a Trust Makes Sense",
    whenWillMakeSenseTxt: "When a Will Makes Sense",
    trustCardDescTxt: "A Trust lets you manage and distribute your assets privately, without court involvement.",
    willCardDescTxt: "A Will outlines your intentions so the court can carry them out if you're unable to.",
    moreAboutTrustTxt: "More About Trusts",
    moreAboutWillTxt: "More About Wills",
    generalTxt: "General",
    diffBtwWillAndTrustTxt: "What is the difference between a Will and a Trust?",
    diffbtwWillAndTrustDescTxt: "A Will is a legal document that outlines how your assets should be distributed after your death and goes through probate court. A Trust is a legal arrangement that allows you to manage and distribute assets privately, avoiding probate and providing more control over your estate.",
    howLongTakeCompleteWillOrTrustTxt: "How long will it take to complete my Will or Trust?",
    howLongTakeCompleteWillOrTrustDescTxt: "With FastWill, you can complete your Will in about 15-30 minutes. A Trust typically takes 30-45 minutes. The process is simple, guided, and you can save your progress and return anytime.",
    doesWillOrTrusthasTobeNotarizedTxt: "Does my Will or Trust have to be notarized?",
    doesWillOrTrusthasTobeNotarizedDescTxt: "Yes, both Wills and Trusts need to be notarized to be legally valid. FastWill offers remote notarization services, so you can complete everything from home without visiting a notary office.",
    whenShouldUpdateWillOrTrustTxt: "When should I update my Will or Trust?",
    whenShouldUpdateWillOrTrustDescTxt: "You should update your Will or Trust after major life events like marriage, divorce, having children, buying property, or significant changes in your financial situation. FastWill provides 30 days of free updates, or you can purchase a Lifetime Membership for ongoing flexibility.",
    doIneedAttorneyToUpdatemyWillTxt: "Do I need an attorney to update my Will?",
    doIneedAttorneyToUpdatemyWillDescTxt: "No, you don't need an attorney to update your Will with FastWill. FastWill offers unlimited edits to your plan, so you can easily make updates as your life changes. Just be sure to have your documents notarized whenever you make changes to keep them legally valid. While it's not required, some people choose to consult an attorney to review their plan and ensure everything is set up properly.",
    canWriteWillForSomeoneelseTxt: "Can I write a Will for someone else?",
    canWriteWillForSomeoneElseDescTxt: "No, you can't write a Will for someone else, but you can help them! A Will must be created by the person it applies to, since it reflects their own wishes. If you get stuck or have questions, FastWill's live support team is always here to help.",
    whatHappenedIfDontHaveWillTxt: "What happens if I don't have a Will?",
    whatHappenedIfDontHaveWillDescTxt: "If you die without a Will, your state's intestacy laws determine how your assets are distributed. This may not align with your wishes, and the process can be lengthy and costly for your loved ones.",
    doesWillProtectFromProbateTxt: "Does a Will protect me from probate?",
    doesWillProtectFromProbateDescTxt: "No, a Will does not avoid probate. It goes through the probate court process, which can be public and time-consuming. A Trust, on the other hand, can help you avoid probate and keep your estate matters private.",
    areOnlineWillLTrustegitTxt: "Are online Wills and Trusts legit?",
    areOnlineWillLTrustegitDescTxt: "Yes, online Wills and Trusts created through FastWill are legally valid when properly executed and notarized. Our documents comply with state-specific requirements and are created using attorney-reviewed templates.",
    howDoIFindMyTrustTxt: "How do I fund my Trust?",
    howDoIFindMyTrustDescTxt: "To fund your Trust, you transfer ownership of your assets into the Trust's name. This includes real estate (through a deed transfer), bank accounts, investments, and personal property. FastWill offers deed transfer services to help you properly fund your Trust.",
    diffBtwRevocAndIrevocTrustTxt: "What is the difference between a Revocable and Irrevocable Trust?",
    diffBtwRevocAndIrevocTrustDescTxt: "A Revocable Trust can be modified or revoked at any time during your lifetime, giving you flexibility and control. An Irrevocable Trust cannot be easily changed once created and is typically used for tax planning or asset protection purposes.",
    shouldSpouseHaveSeparateTrustTxt: "Should my spouse and I have separate Trusts?",
    shouldSpouseHaveSeparateTrustDescTxt: "It depends on your situation. Many couples create a joint Trust that holds assets for both spouses. However, separate Trusts may be beneficial if you have different beneficiaries, want individual control, or have complex estate planning needs. FastWill can help you determine the best approach for your situation.",
    willsTxt: "Wills",
    trustsTxt: "Trusts",
    probateAssetGuideTxt: "Probate Assets: Complete Guide",
    probatePreedingGuideTxt: "Probate Proceedings: Complete Guide",
    probateAfterDeathTxt: "What is probate after death and how does it work?",
    createTrustThatWorksTxt: "Create a Trust That Works for You",
    createYourWillTxt: "Create Your Will In Minutes",
    estatePlaningExpTxt: "Estate Planning Explained",
    buildYourBusinessTxt: "Build Your Business in a",
    modernEstatePlaningSimplePricTxt: "Modern Estate Planning, Simple Pricing",
    willTxt: 'Will',
    pricingTxt: "Pricing",
    trustTxt: 'Trust',
    learnTxt: 'Learn',
    professionalsTxt: 'Professionals',
    logInTxt: 'Log In',
    startTodayTxt: 'Start Today',
    privacyPolicyTxt: "Privacy Policy",
    summaryOfKeyPointsTxt: "SUMMARY OF KEY POINTS",
    termsServiceTxt: "Terms of Service",
    agreementToOurLegalTermsTxt: "AGREEMENT TO OUR LEGAL TERMS",
    needHelpTxt: "NEED HELP?",
    howWeCanHelpTxt: "How can we help?",
    pricingURL: "plans-and-pricing",
    trustPageURL: 'trust-package',
    willPageURL: 'will-package',
    learnPageURL: 'estate-planning-guide',
    professionalsURL: "professionals",
    professionalsPageURL: 'financial-advisors',
    privacyPolicyPageURL: 'privacy-policy',
    termsServicesPageURL: 'terms-of-service',
    welcomeFastWillURL: "will-creation",
    loginPageURL: 'login',
    linkedInPage: 'fastwill',
    fastWillTxt: "FastWill",
    selectDateTxt: "Select Date",
    pleaseLoginToAccountTxt: "Please log in to your account",
    welcomeFastwillTxt: 'Welcome to FastWill',
    headingFirstNameTxt: "First, what's your name?",
    namePlaceholderTxt: 'Enter your name',
    enterPromoCodePlaceholderTxt: "Enter promo code",
    applyTxt: "Apply",
    continueTxt: "Continue",
    logoutTxt: 'Log out',
    statPlaceHolderText: 'Search for your state...',
    avoidProbateYes: "Yes, I'd like my estate to avoid probate.",
    avoidProbateNo: "No, I'm ok with my estate going through probate.",
    paymentSuccessDeedTransferTxt: "Payment successful! Processing your deed transfer order...",
    deedTransferConfirmedTxt: "Your Deed Transfer Is Confirmed!",
    preparingDeedCapTxt: "PREPARING DEED",
    continueWithEmailTxt: 'Continue with email',
    createAccountTxt: 'Create Account',
    selectThisBundleTxt: 'Select This Bundle',
    selectWillBundleTxt: "Select Will Bundle",
    selectWillOnlyTxt: "Select Will Only",
    selectTrustOnly: "Select Trust Only",
    paymentTxt: 'Payment',
    gotoDashboard: "Go to Dashboard",
    viewDashBoardTxt: "View Dashboard",
    dashboard: "Dashboard",
    documentsTxt: "Documents",
    estatePlanTxt: "Estate Plan",
    myDocumentsCapTxt: "MY DOCUMENTS",
    legacyContactsTxt: "Legacy Contacts",
    addTrustedLegacyContactToYourAccountTxt: "Add a trusted Legacy Contact to your account to make sure someone you trust can access your documents in an emergency.",
    backToOverview: "Back to Overview",
    financialInstitutionLabel: "Financial institution",
    noTxt: "No",
    exitTxt: "Exit",
    alwaysReceiveCareTxt: "Always Receive Care",
    addAContactTxt: "Add a Contact",
    addAccountTxt: "Add Account",
    petsNameLabel: "Pet's Name",
    amountLabel: "Amount",
    fullNameLabel: "Full name",
    termsCheckboxId: '#terms-checkbox',
    confirmAndPayBtnTxt: 'Confirm & Pay',
    thanksforPurchaseTxt: "Thank you for your purchase!",
    postalCodePlaceHolder: 'M5T 1T4',
    cvcPlacholder: 'CVC',
    expireyPlaceholder: 'MM / YY',
    cardNumberPlaceholder: "1234 1234 1234 1234",
    whatYourAddressTxt: "What is your address?",
    whatisYourbirthdayTxt: "Great! Now, what is your birthday?",
    doYouHaveChildTxt: "Do you have children?",
    haveChildrenTxt: "have children?",
    nameOfYourTrustTxt: "Name of your Trust",
    guardianNominationTxt: "Do you want to name a guardian for your children?",
    whatIsSpousenameTxt: "What's your spouse's name?",
    whoLookAfterYourChilderenTxt: "Who would you like to look after",
    wouldYouLikeNameConservatorChild: "Would you like to name a conservator for your children?",
    whoWouldYouLiketoNameAsConservator: "Who would you like to name as the conservator?",
    futureAdoptionChildrenWillTxt: "Would you like to include any future or adopted children in your Will?",
    whichChildWouldULikeToAssignTxt: "Which children would you like to assign guardians for?",
    testLivingTrustTxt: "Perfect. Would you like the Trust to be called the “Test Living Trust”?",
    whenWouldYouBeginTrust: "When would you like your Trust to begin?",
    gatherInfoAboutChilderenTxt: "Let's gather a few important details about your children.",
    wouldYouMainPersonToManageTrustTxt: "Will you be the main person managing this Trust while you're alive?",
    areYouAsGrantorTxt: "Are you, as a Grantor, also the lifetime beneficiary?",
    wholWillLifetimeBeneficiaryTxt: "Who will be the lifetime beneficiary of the Trust?",
    whoShouldTrusteeIncapacitatedTxt: "Who should take over if the Trustee is incapacitated?",
    whoWouldTakeOverPassAwayTxt: "Who should take over if the Trustee passes away?",
    doYouHavePetTxt: "Do you have any pets?",
    doYouWantChoosePetGuardianTxt: "Do you want to choose guardians for any of your pets?",
    listOfPetsDescTxt: "Okay, let's list each of your pets you'd like to nominate guardians for:",
    petGuardianAssignmentTxt: "Who would you like to look after ",
    setAsideMoenyToCaringPersonHelp: "Would you like to set aside some money to help the person caring for your pets?",
    currentAddressPropTxt: "Is your current address one of your properties?",
    beneficairyReceiveInheritanceTxt: "Should your beneficiaries receive their inheritance right away?",
    whatAgeBeneReceiveAssetsTxt: "At what age do you want the beneficiaries to receive their assets?",
    wouldBeneficHavRightEarlyWithdrawTxt: "Would you like your beneficiaries to have the right to Early Withdrawal of Principal at a Specified Age?",
    beneficBeAbleToWithdrawTxt: "When should your beneficiaries be able to Withdraw from the Principal?",
    howLongbeneficliveAfterPasstoInheritTxt: "How long must beneficiaries live after your passing to inherit?",
    wantExludeFromWill: "Do you want to exclude anyone from your Will?",
    finalRestingPlaceTxt: "What would you like as your final resting place?",
    shouldExecutorRequiredBond: "Should the executor be required to get a bond?",
    howMuchForBondTxt: "How much should the bond be for?",
    wantBackupExecutor: "Do you want to name a backup executor?",
    whoWillbeExecutorTxt: "Who will be your executor?",
    whoWillbeBackupExecutorTxt: "Who will be your backup executor?",
    weAreGoingAssetSectionTxt: "We're going to the Assets section now",
    wouldYouLikeProtectWillFromPotentialDesputeTxt: "Would you like to protect your Will from potential disputes?",
    wantNameBackupHealthAgentTxt: "Do you want to name a backup healthcare agent?",
    whoWillBackupAgentTxt: "Who will be your backup healthcare agent?",
    wantToMonitorTxt: "Do you want to name a monitor?",
    whoWouldLikeNameasMonitorTxt: "Who would you like to name as the Monitor?",
    wantNameConservatorEstateTxt: "Do you want to name a conservator for your estate?",
    wantNominateGuardianForSelfTxt: "Do you want to nominate a guardian for yourself?",
    whoWillMakeMedicalDecision: "Who will make medical decisions for you if you can't?",
    haveSpecialRequestforCremony: "Do you have any special requests or instructions for your ceremony?",
    willSpousebeMainManaingTrustTxt: "Will you and your spouse be the main people managing this Trust while you're alive?",
    questionSymbol: "?",
    resetPasswordTxt: "Reset password",
    acceptCookiesTxt: "Accept Cookies",
    notary9To5AmTxt: "Notary sessions can only be created between 9 AM and 5 PM in your timezone.",
    notaryCreateSessionTxt: "Create Notary Session",
    notaryCreatedSuccessMessage: "Notarization session created successfully!",
    joinSessionNowTxt: "Join Session Now",
    addressLine1Placeholder: "123 Main St",
    addressLine2Placeholder: "Apt 4B",
    cityPlaceholder: "San Francisco",
    zipCodePlaceholder: "94102",
    countryPlaceholder: "United States",
    selecteDatePlaceholder: "Select date",
    childNamePlaceholder: "e.g. Charles Edison",
    yesTxt: "Yes",
    addChildTxt: /Add (a )?Child/,
    meTxt: "Me",
    selectBirthdayFieldPlaceholder: "Select date of birth",
    saveTxt: "Save",
    forgetPasswordTxt: "Forgot password?",
    newYorkTxt: "New York",
    addContactTxt: "Add Contact",
    addConservator: "Add a Conservator",
    addPetTxt: "Add a Pet",
    addAddress: "Add Address",
    addPropertyTxt: "Add Property",
    addAccountTxt: 'Add Account',
    businessTypePlaceHolderTxt: "e.g., Solo Proprietorship",
    privacyTypePlaceHolderTxt: 'e.g., Term Life',
    calculatingTxt: "Calculating...",
    totalTxt: 'Total',
    totalNotarizationTxt: 'Notarization Total',
    notarizationTxt: "Notarization",
    howItWorksTxt: "How it works",
    securePaymentToDeedTransferTxt: "Secure your payment to begin your deed transfer",
    getStartedTxt: "Get Started",
    deedTransferCalculationTxt: "Deed Transfer Calculation",
    addressTxt: "Address",
    whatYoullNeedTxt: "What You'll Need",
    previewTxt: "Preview",
    downloadTxt: "Download",
    downloadAllTxt: "Download All",
    manageSharingAccessTxt: "Manage Sharing Access",
    saveChangesTxt: "Save Changes",
    forBothOfUsTxt: "For both of us",
    backTxt: "BACK",
    justMeTxt: "Just me",
    cancelTxt: "Cancel",
    trustBaseEstatePlanTxt: "Trust-Based Estate Plan",
    willBaseEstatePlanTxt: "Will-Based Estate Plan",
    wouldLikeTorAvoidProbatProcessTxt: "Would you like to avoid the probate process?",
    magicAddAnnualSubscTxt: "Magic Add Annual Subscription",
    addFastWillLifeTimeMembTxt: "Add FastWill Lifetime Membership",
    subscAllowEditDocumentTxt: "Subscription allows you to edit your documents anytime.",
    succfullyUpdateAccessForTxt: "Successfully updated access for",
    getStartedNotarizingTxt: "Get Started Notarizing",
    lastWillAndTestament: "Last Will & Testament",
    advanceCareDirectiveTxt: "Advance Care Directive",
    powerOfAttorneyTxt: "Power of Attorney",
    pourOverWillTxt: "Pour-Over Will",
    revocableLivingTrustTxt: "Revocable Living Trust",
    scheduleOfAssetsTxt: "Schedule of Assets",
    fundingInstructionTxt: "Funding Instructions",
    certificationOfTrustTxt: "Certification of Trust",
    wouldLiktoPurchase5Each: "I'd like to purchase witnesses – $5 each",
    twoProfessionalWitnessesTxt: "2 professional witnesses",
    estatePlanDocumenTxt: "Estate Plan Document(s)",
    notaryWitnessesTxt: "Notary Witnesses",
    witnessSpouseEmailPlaceholder: "ex: jane@example.com",
    deedTranserTotalTxt: "Deed Transfer Total",
    subtotalTxt: "Subtotal",
    spouseInputPlaceHolder: "e.g. Thomas Edison",
    thomasEdisonName: "Thomas Edison",
    radioButtonChecking: "Checking",
    valueOfAllAsset: "Up to $50k",
    welcomeAmbreenTxt: "Welcome, Ambreen!",
    overviewTxt: "Overview",
    summaryTxt: "Summary",
    nextStepCardsTxt: "NEXT STEPS",
    notarizeNowTxt: "Notarize Now",
    addNowTxt: "Add Now",
    sendInviteTxt: "Send Invite",
    nameLabel: "Name",
    ambreenTestName: "Ambreen Test",
    ambreenTest123Name: "Ambreen Test 124",
    oliverBennettName: "Oliver Bennett",
    recommendedBasedOnYourAnsTxt: "Here's what we recommend for you based on your answers",
    passwordResetMailSentSuccessTxt: "We have emailed your password reset link.",
    timeToMakeYourPlanOfficialTxt: "It's time to make your plan official in Alabama!",
    legacyContactFullnameLabel: "Enter your contact's full name",
    legacyContactEmailLabel: "Enter your contact's email",
    invitationSentSuccessTxt: "Invitation sent successfully!",
    updatedDocumentAccessTxt: "Successfully updated document access for",
    anyLimitForHealthTxt: "Any limits for your health care agent?",
    wantDonateOrganTxt: "Do you want to donate your organs?",
    previousPowerofAttorneyDocumentTxt: "Do you want to revoke any previous Power of Attorney documents?",
    screenOfFinancialAgentTxt: "Who should handle your finances if you can't?",
    wantNameBackupFinancialAgenTxt: "Would you like to name a backup financial agent?",
    successorAgenScreenDisplayed: "Who would you like to name as backup agents if your primary agent is unable to serve?",
    wouldLikeBackRuleForBackAgetntxt: "Would you like to add backup rules for the backup agent to become the main agent?",
    whatTypeDecisionsAthorityToAgent: "What type of decisions can",
    wantWhenHealthProxyNoLongerEffectTxt: "Do you want to choose a date or event when your Health Care Proxy will no longer be in effect?",
    modifyStandardPowerAttorneyTxt: "Would you like to make any modifications to the standard Power of Attorney?",
    wouldLikeGivePermissionViewMedicalRecordsTxt: "Would you like to give any other people permission to view your medical records?",
    shouldAgentGiveGiftsTxt: "Should your agent be able to give gifts over $5,000?",
    leaveAnySpecialInstructions: "Would you like to leave any special instructions?",
    pwrAtteroneyExpire: "Do you want your Power of Attorney to expire on a set date or event?",
    leaveOutGiftingIntentionaly: "Do you want to leave out the gifting option intentionally?",
    leaveMedicalCarforAgentTxt: "Do you want to leave medical care instructions for your agent?",
    selectTaskYounWantYourHealthCarAgentManageTxt: "Select the tasks and decisions you want your health care agent to manage.",
    yourMedicalCareInstructionsTxt: "Your medical care instructions",
    typeInstuctionHereTxt: "Type your instructions here",
    shouldAgenActTogetherTxt: "Should your agents act together or independently?",
    realPropertyExpandedDetailTxt: "Your agent has authority to manage, buy, sell, mortgage, and lease real property including land and buildings on your behalf.",
    beAbleToHelpWithTxt : "be able to help with?",
    actTogetherTxt: "Act Together",
    learnMoreTxt: "Learn More",
    whenWas: `When was `,
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    phone: "Phone",
    location: "Location",
    addAnotherTxt: "Add Another",
    numberOfDaysLabel: "Number of Days",
    agePlaceHolderTxt: "Enter age (0-100)",
    myDecendentsTxt: "My Descendants",
    perStirpesTxt: "Per Stirpes",
    perRepresentationTxt: "Per Representation",
    perCapitaTxt: "Per Capita",
    addressLine1: "Address line 1",
    addressLine2: "Address line 2",
    addresLine2Option: "Address Line 2 (Optional)",
    addressLine2Property: "Address line 2 (apt, floor, ste, etc)",
    approximateValue: "Approximate value (optional)",
    approxmateAccountValue: "Approximate account value (optional)",
    estimateValueLabel: "Estimated value (optional)",
    nameOfPersonOrOrganizationLabel: "Name of the person or organization",
    cremonyTypeTxt: "What type of ceremony would you like to have?",
    cremationTxt: "Cremation",
    memorialServiceTxt: "Memorial Service",
    myRequestLabel: "My request",
    addHealthCareAgentTxt: "Add a Healthcare Agent",
    organsNeededEyesTissuesTxt: "Any needed organs, eyes and/or tissues",
    followOrgansEyesAndTissuesTxt: "The following organs, eyes and/or tissues",
    authorizedPersonTxt: "Authorized Person",
    yesIwouldLikeToChooseTxt: "Yes, I'd like to choose",
    noEndMyRequestTxt: "No, End it at my Request",
    thisProxyShallExpireLabel: "This proxy shall expire (specific date or conditions)",
    financialCareSectionTxt: "We're going to the Financial Care section now",
    addFinancialAgentTxt: "Add a Financial Agent",
    addBackupAgentTxt: "Add Backup Agent",
    describeBackupRuleLabel: "Describe your backup rules",
    realPropertyTxt: "Real Property",
    taxesTxt: "Taxes",
    hipaaAuthorizationTxt: "HIPAA Authorization",
    anySpecificRestrictionLabel: "Any specific restrictions?",
    yourSpecialInstructionsLabel: "Your special instructions",
    provideEvenOrDateLabel: "Provide event or date",
    guardianTxt: "Guardian",
    childrenTxt: "Children",
    addPolicyTxt: "Add Policy",
    policyCarrierTxt: "Policy carrier",
    valuePolicyLabel: "Value of policy (optional)",
    addIntrestTxt: "Add Interest",
    businessNameLabel: "Business name",
    valueOfOwnershipLabel: "Value of ownership (optional)",
    addItemTxt: "Add Item",
    itemNameLabel: "Item name",
    briefDescriptionLabel: "Brief description",
    inputTxt: "input",
    city: "City",
    state: "State",
    countyTxt: "County",
    ownerTxt: "Owner",
    zipCode: "Zip Code",
    zipPostalCode: "Zip/Postal code",
    country: "Country",
    assetTxt: "Assets",
    editAssetsTxt: "Edit Assets",
    otherTxt: "Other",
    businessesTxt: "Businesses",
    businessIntrestTxt: "Business interests",
    recordingFeesTxt: "Recording Fees",
    summaryServiceTxt: "Summary Service",
    brickellAvenueTxt: "1111 Brickell Avenue",
    metLifeInsuranceTxt: "MetLife Insurance",
    lifeInsuranceTxt: "Life Insurance",
    arrangementsTxt: "Arrangements",
    michealAndersonName: "Michael Anderson",
    memorialServicesTxt: "memorial-service",
    healthCareTxt: "Health Care",
    sarahWilliamName: "Sarah Williams",
    yesAnyTxt: "Yes - Any",
    financialsTxt: "Financials",
    financialAccountsTxt: "Financial accounts",
    propertiesTxt: "Properties",
    davidMillerName: "David Miller",
    manageAccessTxt: "Manage Access",
    editTxt: "Edit",
    confirmTxt: "Confirm",
    doneTxt: "Done",
    hipaaCapTxt: "HIPAA",
    upgradeGiftTxt: "Upgrade Gift",
    referAFriendTxt: "Refer A Friend",
    gift20PercentOffToYourFriendTxt: "Gift 20% Off to Your Loved Ones",
    enterLoveoneNameLabel: "Enter your loved one's first name",
    enterLoveOneEmailLabel: "Enter your loved one's email",
    settingsTxt: "Settings",
    updateProfileTxt: "Update Profile",
    deedTranserTxt: "Deed Transfer",
    profileUpdateSuccessTxt: `Profile updated successfully!`,
    currentPasswordLabel: "Current Password",
    newPasswordLabel: "New Password",
    confirmNewPassLabel: "Confirm New Password",
    updatePasswordTxt: "Update Password",
    passUpdateSuccessTxt: `Password updated successfully!`,
    sharePlanWithSomeoneYouTrustTxt: "Share Your Plan With Someone You Trust",
    accessRemovedSuccessTxt: "Access removed successfully.",
    addTrustedLegacyContactaccountTxt: "Add a trusted Legacy Contact to your account to make sure",
    firstAgeOfBenefTxt: "First Age of Beneficiary Withdrawal (in years)",
    firstWithdrawalPercentageTxt: "First Withdrawal Percentage",
    secondAgeOfBenefTxt: "Second Age of Beneficiary Withdrawal (in years)",
    secondWithdrawalPercentageTxt: "Second Withdrawal Percentage",
    shareMyPlanTxt: "Share My Plan",
    contactNameTxt: "Contact Name",
    emailAddressTxt: "Email Address",
    distrubutionTxt: "Distribution",
    addTxt: "Add",
    updatePropertyTxt: "Update Property",
    realEstateTxt: "Real Estate",
    addPersonTxt: "Add Person",
    savingsTxt: "Savings",
    relationshiptToBisnessPlaceholder: "e.g., Owner",
    enterTxt: "Enter",
    promotCodeTxt: "Promo code",
    sharePlanTxt: "Share Plan",
    selectContactTxt: "Select Contact",
    selectContact11Txt: "Select Contact 11",
    conservatorBondTxt: "Do you want to require your conservator to post a bond?",
    nominateBackupEstateConserTxt: "Would you like to nominate a backup estate conservator?",
    pleaseProvideAccountDetailTxt: "Please provide details about your financial accounts.",
    doyouHaveFinancialAccountTxt: "Do you have any financial accounts?",
    doyouHaveLifeInsuranceTxt: "Do you currently have life insurance?",
    pleaseProvideDetailsLifeInsuTxt: "Please provide details about your life insurance policies.",
    doyouHaveBusinessIntrestTxt: "Do you have any business interests?",
    pleaseProvideBusessIntrestTxt: "Please provide details about your business interests.",
    dyouHaveItemsTxt: "Do you have any other items that are important to you?",
    provideDetailsAboutItemsTxt: "Please provide details about these other items.",
    howToDistributePersonalPropertyTxt: "How would you like to distribute your tangible personal property (furniture, jewelry, collectibles, etc.)?",
    howToDivideTangibleProprtyTxt: "How would you like to divide your tangible property among beneficiaries?",
    howyouLikeResiduaryDistrubutedTxt: "How would you like your residuary distributed?",
    wantToSplitResiduaryTxt: "Do you want to split your residuary evenly among all beneficiaries?",
    backupResiduaryDistributedTxt: "How would you like your Backup Residuary distributed?",
    customePercentageTxt: "Custom Percentages",
    divideEvenlyTxt: "Divide Evenly",
    whoWouldBeTrusteeTxt: "Okay, who should be the Trustee?",
    promoCodeAppliedSuccessTxt: "Promo code applied discount reflected in total.",
    invitationSentTxt: "Invitations Sent!",
    whatisValueOfAssetsTxt: 'What is the value of all your assets?',
    doyouHaveAnyPropertyTxt: "Do you have any property?",
    provideDetailOfPropertyTxt: "Please provide details about your properties.",
    updateProfileInfoToManageTxt: `Update your profile information and manage your account settings.`,
    enterValidEmailError: "Please enter a valid email address with a proper domain extension (e.g., .com, .org).",
    emailRegisteredError: "This email is already registered. Please log in or use a different email.",
    passwordError: "A password is required.",
    invalidCredentialsError: "These credentials do not match our records.",
    noAccountFoundError: "No account found with that email address.",
    passwordLengthError: "The password must be at least 5 characters long.",
    cardNumberIncompleteError: "Your card number is incomplete.",
    cardExpiryDateIncompleteError: "Your card’s expiration date is incomplete.",
    cardCVCIncompleteError: "Your card’s security code is incomplete.",
    cardPostalCodeError: "Your postal code is invalid.",
    cardNumberInvalidError: "Your card number is invalid.",
    caringPersonAmountError: "Please enter a reward amount if offering a pet reward.",
    promoCodeError: "Promo Code Not Recognized. Please try again.",
    zipcodeFormatError: "Zip Code field format is invalid.",
    fieldRequiredError: "Field is required.",
    emailRequiredError: "Email is required.",
    emailFormatError: "Email must be a valid format.",
    invalidEmailError: "Please enter a valid email address.",
    phoneNumberRequiredError: "Phone number is required.",
    invalidUSPhoneError: "Please enter a valid US phone number (e.g. +1 (555) 123 - 4567).",
    addressLine1RequiredError: "Address line 1 is required.",
    addressLCapLine1RequiredError: "Address Line 1 is required.",
    cityRequiredError: "City is required.",
    stateRequiredError: "State is required.",
    zipcodRequiredError: "ZIP code is required.",
    zipCodeRequiredError: "Zip code is required.",
    zipcod5DigitError: "ZIP code must be exactly 5 digits.",
    zipCodeDigitError: "Zip code must be exactly 5 digits.",
    firstNameRequiredError: "First name is required.",
    petNameRequiredError: "Pet name is required.",
    lastNameRequiredError: "Last name is required.",
    distributionError: "Total distribution must equal 100%.",
    policyCarrierError: "Policy carrier is required.",
    policyTypeError: "Policy type is required.",
    businessNameError: "Business name is required.",
    businessTypeError: "Type of business is required.",
    financialInstitutionRequiredError: "Financial institution is required.",
    selectAtleastOneTypeError: "Select at least one account type.",
    itemNameError: "Item name is required.",
    itemDescError: "Description is required.",
    pleaseSelectAtleastOneOptionError: "Please select at least one option (Spouse, Children, or add a person) before continuing.",
    totalShould100PercentError: "Total must be equal to 100%.",
    enterPercEachBenefError: "Please enter a percentage for each beneficiary when dividing property unequally.",
    ageDistributionError: "Please enter an age of distribution.",
    ageShouldBtwBeError: "The age of distribution must be between 0 and 100.",
    numberOfSurvivorshipError: "Please enter the number of survivorship days.",
    numberShouldBtwError: "Please enter a number between 1 and 365.",
    percentagesMustBe100PercentageError: "The percentages must add up to 100%. They currently add up to",
    ageForWithdrawalError: 'Please provide the age for withdrawal.',
    withdrawalLevelError: "Please provide the withdrawal level 1 percentage.",
    withdrawTrustAgeMustBeZeroError: "The trust.age of withdraw field must be at least 0.",
    withdrawL1PercentageBtwError: "Withdrawal level 1 percentage must be between 0 and 100.",
    withdrawL2PercentageBtwError: "Withdrawal level 2 percentage must be between 0 and 100.",
    mustBeLessAgeOfDistruError: "Must be less than Age of Distribution",
    bondAmounError: "The bond amount is required.",
    guardianError: "Please select a guardian.",
    disinheritanceError: "The disinherit name is required.",
    backupConservatorError: "Please select a backup estate conservator when you choose to have one.",
    invalidBondAmountError: "The bond amount is invalid (allowed values $100 – $100,000,000).",
    specialRequestDetailError: "Please provide details in the request content when special requests is Yes.",
    specialRequestYesError: "Since you chose “Yes” for a special request, please provide the details.",
    donateOrganError: "Please specify the type of organs to donate when organ donation is selected.",
    authorizationPersonError: "The user.authorized person full name field is required when Other Access is 1.",
    expirationDetailError: "Since you chose “Yes” for expiration, please provide the expiration details.",
    provideBackupRulesError: "Please provide backup rules content when backup rules is Yes.",
    specialInstructionError: "Please provide special instructions to proceed.",
    powerOfAttorneyError: "Please provide an event or date for terminating the Power of Attorney.",
    passwordFiledConfirmNotMatchError: "The password field confirmation does not match.",
    parentRatioBtnTxt: (name) => `${name} and Me`,
    youReferralInviteSentToEmailTxt: (email) => `Your referral invitation has been sent to ${email}.`,

    /** ids path */
    contactNameId: "#contactName",
    contactEmailId: "#deliverTo",
    emailId: '#email',
    passwordId: '#password',
    accountPasswordId: "#account-password",
    confirmPasswordId: "#password_confirmation",
    messengerFramId: '#widgetMessengerFrame',
    wiilCreateHeaderCorssIconId: "#will-creation-header button",
    paymentFormId: "#payment-form",

    /** xpaths */
    editPetXpath: 'button:has(img[alt="Edit"])',
    deletePetXpath: 'button:has(img[alt="Delete"])',
    pamentFrameXpath: 'iframe[title="Secure payment input frame"]:not([aria-hidden="true"])',
    xPathProfile: 'a[aria-label="Settings"]+div>button',
    xpathAccountDropdown: 'a[aria-label="Settings"]+div>div',
    checkValueForLabelXpath: 'xpath=following-sibling::*[1]',
    datePickerYearXpath: "//button[contains(@id,'datepicker_') and contains(@id,'_year_btn')]",
    datePickerTrustXpath: "//input[contains(@id,'datepicker_') and contains(@id,'_input')]",
    datePickerMonthXpath: "//button[contains(@id,'datepicker_') and contains(@id,'_month_btn')]",
    xpathAddPrimaryGuardianButton: "//div[label[normalize-space()='Primary Guardian']]//button",
    xpathBackupGuardianButton: "//span[normalize-space()='Backup Guardian']/following-sibling::button",
    xpathAddContactPrimaryGuardianButton: "(//h2[normalize-space()='Select Contact']/following-sibling::div/button)[1]",
    xpathAddContactBackupGuardianButton: "(//h2[normalize-space()='Select Contact']/following-sibling::div/button)[2]",
    modelCrossIcon: "//a[contains(@href, 'estate-checklist')]/following-sibling::button[img[@alt='Close']]",
    assetsTab: "//button[normalize-space()= 'Summary']/following-sibling::button[normalize-space()='Assets']",
    previewDocumentModelCloseIco: "//a[contains(@href, 'download/user')]/following-sibling::button[img[@alt='Close']]",
    basicXPath: "(//span[normalize-space()='Basic'])[2]",
    closeIcon: "(//div[a[contains(@href, 'dashboard/user')]])[1]/following-sibling::div/button",
    closeInviteModel: "//div[h2[contains(text(), 'Refer A Friend')]]/following-sibling::button",
    manageAccessHipaXPath: "//div[div[h3[normalize-space()='HIPAA']]]/following-sibling::div/button[normalize-space()='Manage Access']",
    downloadHipaaDocumentXpath: "//div[div[h3[normalize-space()='HIPAA']]]/following-sibling::div/a[normalize-space()='Download']",
    removeAccessModelBtnXpath: "//div[h2[normalize-space()='Remove Legacy Contact']]/following-sibling::div/button[normalize-space()='Remove Access']",
    feeItemsXpath: "(//div[h3[normalize-space()='Recording Fees']/following-sibling::div])/div",
    totalFeeAmountXpath: "xpath=//span[normalize-space()='Total Recording Fees']/following::span[2]",
    deedTransferNotFeeXpath: "//span[normalize-space()='Amount']/following-sibling::span",
    recordingFeeItemsCountXpath: "xpath=./div",
    recordingFeeRowXpath: "(//span[normalize-space()='Recording Fees'])/following-sibling::div",
    totalPriceXpath: "(//div[span[normalize-space()='Total']])[2]/following-sibling::span",
    propertyAmountXpath: "//div[div[normalize-space()='Real Estate']]//following-sibling::div[.//div[starts-with(normalize-space(), '$')] and not(preceding-sibling::div[div[normalize-space()='Financial accounts']])]//div[starts-with(normalize-space(), '$')]",
    sideDeedTransferXPath: "//aside[contains(@class, 'lg:block')]/nav/div/ul/li/a[./span[normalize-space()='Deed Transfer']]",
    dropdownXpath: '//div[@x-show="open" and not(contains(@style, "display=none"))]',
    byLableInputXpath: 'xpath=following-sibling::div//input[not(contains(@type, "hidden"))]',
    inputTxtByLabelXpath: 'xpath=following-sibling::div//input',
    addPropertyBtnXpath: "//div[div[h2[normalize-space()='Add a property' ]]]//button[normalize-space()='Add Property']",
    textAreaXpath: 'xpath=following-sibling::textarea',
    sendInvitepopupXpath: "//button[normalize-space()='Send Invite']",
    sendInviteBtnXpath: "//h2[normalize-space()='Contact Information']/following-sibling::div[2]/button",
    totalAmountForCreateAccountXpath: "//div[div[p[normalize-space()='Total']]]//p[contains(normalize-space(), '$')]",
    recordingFeeRowPriceItemXpath: (index) => `(//span[normalize-space()='Recording Fees'])[${index}]/following-sibling::div/span[last()]`,
    recordingFeeItemXpath: (index) => `(//div[h3[normalize-space()='Recording Fees']/following-sibling::div])[${index}]/div/div[1]/div/div[contains(@class,'items-end')]/span[2]`,
    amountByLabelXpath: (label) => `(//span[normalize-space()='${label}'])[2]/following-sibling::span`,
    selectStateFromDropdown: (state) => `xpath=.//div[span[normalize-space()="${state}"]]`,
    valueByDivLabelXpath: (label) => `//div[normalize-space()='${label}']/following-sibling::div`,
    documentTitleXpath: (title) => `//div[div[div[h3[normalize-space()='${title}']]]]`,
    sideBarLinkXpath: (title) => `//aside[contains(@class, 'lg:block')]/nav/div/ul/li/a[./span[normalize-space()='${title}']]`,
    selectContactEmailXpath: (email, btnTxt) => `//div[./button[normalize-space()='${btnTxt}']]/preceding-sibling::div/div/label/div[./div[text()='${email}']]`,
    manageAccessBtnUsingEmailXpath: (email) => `//div[div[span[normalize-space()='${email}']]]/following-sibling::div/button[normalize-space()='Manage Access']`,
    removeAccessForContactsUsingEmailXpath: (email) => `//div[div[span[normalize-space()='${email}']]]/following-sibling::div/button[normalize-space()='Remove Access']`,
    tabsUsingBaiscTabXpath: (text) => `(//span[normalize-space()='Basic'])[2]/following::span[normalize-space()='${text}']`,
    selectContactXpath: (name) => `(//div[div[span[normalize-space()='${name}']]]/following-sibling::div/button)`,
    spanTextXpath: (text) => `span:has-text("${text}")`, 
    assetSectionRow: (rowName) => `//div[div[div[normalize-space()='Name / Address']]]//div[div[normalize-space()='${rowName}']]`,
    benefePercentageXpath: (name) => `//div[span[normalize-space()='${name}']]//input`,
    showMoreButtonXpath: (name) => `//div[span[normalize-space()='${name}']]/following-sibling::button`,
    editContactButtonXpath: (name) => `//div[div[div[div[span[normalize-space()='${name}']]]]]//button/img`,
    contactPersonXpath: (name) => `//div[div[div[div[span[normalize-space()='${name}']]]]]`,
    contactViewXpath: (category) => `img[alt='${category}'] + span`,
}

export function getLocator(value) {
    switch (value) {
        case 'Alabama':
        case 'California':
        case 'Florida':
        case 'New York':
        case 'Colorado':
        case 'Alaska':
        case 'Washington':
        case 'Massachusetts':
        case 'Illinois':
            return generalPage.statPlaceHolderText;
        case 'United States':
            return generalPage.countryPlaceholder;
        case 'Solo Proprietorship':
            return generalPage.businessTypePlaceHolderTxt;
        case "Owner": 
        return generalPage.relationshiptToBisnessPlaceholder;
        case 'Term Life':
        case 'Whole Life':
            return generalPage.privacyTypePlaceHolderTxt;
        default:
            throw new Error(`Locator for "${value}" not defined`);
    }
}
