import { allure } from 'allure-playwright';
import { generalPage } from '../pages/general.page';
import { generalSteps } from './general.steps';
const COMMON = require('../utils/common.json');


export const regressionSteps = (page) => {
    const generalStep = generalSteps(page);
    return {
        async individualTrustUserBasicAddressToConservatorSetup(constants) {
            await allure.step("Verify complete Basic Trust end-to-end flow", async () => {
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.enterAddressLine1(constants.addressLine1);
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.enterCity(constants.city);
                await generalStep.selectItemFromDropDown(constants.enterState, constants.selectStateFromDropdown);
                await generalStep.enterZipCode(constants.zipcode);
                await generalStep.selectItemFromDropDown(constants.enterCountery, constants.selectCountryFromDropdown);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.verifyBirthdayScreenIsVisible();
                await generalStep.enterBirthDayDate(constants.birthdayDate);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyDoyouHavChildrenScreenIsVisible();
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.futureAdoptionChildrenWillTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.gatherInfoAboutChilderenTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickAddAChildAndItsDetails(constants.adultChildName, constants.adultChildDOB);
                await generalStep.verifyWithButtonScreenTitleIsVisible(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.guardianNominationTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.futureAdoptionChildrenWillTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.clickAddAChildAndItsDetails(constants.childName);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.guardianNominationTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whichChildWouldULikeToAssignTxt);
                await generalStep.clickChildToAssignToGuardian(constants.childName);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenContainsTheTitle(generalPage.whoLookAfterYourChilderenTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.addPrimaryGuardian();
                await generalStep.addGuardian(constants.primaryParentData, constants.guardianType);
                await generalStep.verifyWithButtonScreenTitleIsVisible(generalPage.continueTxt);
                await generalStep.addBackUpGuardian();
                await generalStep.addGuardian(constants.backupParentData, "");
                await generalStep.verifyWithButtonScreenTitleIsVisible(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldYouLikeNameConservatorChild);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWouldYouLiketoNameAsConservator);
                await generalStep.clickOnAddConservatorButton();
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryParentData.firstName} ${constants.primaryParentData.lastName}`, constants.guardianType);
                await generalStep.clickOnAddContactButtonByIndex(constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.futureAdoptionChildrenWillTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.testLivingTrustTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.inputByLabel(generalPage.nameOfYourTrustTxt, constants.silverOakTrust);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whenWouldYouBeginTrust);
                await generalStep.verifyTrustDatePickerPrepopulated();
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldYouMainPersonToManageTrustTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.areYouAsGrantorTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldYouMainPersonToManageTrustTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWouldBeTrusteeTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.verifyButtonIsDisabled(generalPage.confirmTxt);
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryParentData.firstName} ${constants.primaryParentData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.areYouAsGrantorTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoShouldTrusteeIncapacitatedTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.areYouAsGrantorTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wholWillLifetimeBeneficiaryTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt)
                await generalStep.addGuardian(constants.executorData, constants.guardianType)
                await generalStep.clickOnContinueButton()
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoShouldTrusteeIncapacitatedTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.addGuardian(constants.monitorData, constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWouldTakeOverPassAwayTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.addGuardian(constants.successorData, constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doYouHavePetTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.weAreGoingAssetSectionTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doYouHavePetTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doYouWantChoosePetGuardianTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.weAreGoingAssetSectionTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doYouWantChoosePetGuardianTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.listOfPetsDescTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnAddPetByIndex(1);
                await generalStep.fillInputByLabel(generalPage.petsNameLabel, constants.petName, "");
                await generalStep.clickOnAddPetByIndex(2);
                await generalStep.clickOnSendInviteButton(generalPage.editPetXpath);
                await generalStep.fillInputByLabel(generalPage.petsNameLabel, constants.dogBella, "");
                await generalStep.clickOnAddPetByIndex(1);
                await generalStep.clickOnSendInviteButton(generalPage.deletePetXpath);
                await generalStep.clickOnAddPetByIndex(1);
                await generalStep.fillInputByLabel(generalPage.petsNameLabel, constants.petName, "");
                await generalStep.clickOnAddPetByIndex(2);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyPetGuardianAssignmentScreenIsVisible(constants.petName);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.addPrimaryGuardian();
                await generalStep.addGuardian(constants.primaryPetGuardianData, constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.setAsideMoenyToCaringPersonHelp);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.weAreGoingAssetSectionTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.setAsideMoenyToCaringPersonHelp);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.inputByLabel(generalPage.amountLabel, constants.inValidCaringPersonAmount);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.caringPersonAmountError);
                await generalStep.inputByLabel(generalPage.amountLabel, constants.caringPersonAmount);
                await generalStep.clickOnContinueButton();
            });
        },
    }

}