import { allure } from 'allure-playwright';
import { generalPage } from '../pages/general.page';
import { generalSteps } from './general.steps';
const COMMON = require('../utils/common.json');


export const regressionSteps = (page) => {
    const generalStep = generalSteps(page);
    return {
        async individualTrustUserBasicAddressToConservatorSetup(constants) {
            await allure.step("Verify complete Individual Trust Basic section flow including address, DOB, children logic, trustee conditional flow, successor trustee, pet nomination, guardian nomination, pet reward funding, and completion logic.", async () => {
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.enterAddressLine1(constants.addressLine1);
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.enterCity(constants.city);
                await generalStep.selectItemFromDropDown(constants.enterState, constants.selectStateFromDropdown);
                await generalStep.enterZipCode(constants.zipcode);
                await generalStep.selectItemFromDropDown(constants.enterCountery, constants.selectCountryFromDropdown);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whatisYourbirthdayTxt);
                await generalStep.enterBirthDayDate(constants.birthdayDate);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyDoyouHavChildrenScreenIsVisible();
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.futureAdoptionChildrenWillTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.gatherInfoAboutChilderenTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickAddAChildAndItsDetails(constants.adultChildName, constants.adultChildDOB);
                await generalStep.verifyWithButtonScreenTitleIsVisible(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.futureAdoptionChildrenWillTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.clickAddAChildAndItsDetails(constants.childName);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.guardianNominationTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whichChildWouldULikeToAssignTxt);
                await generalStep.clickChildToAssignToGuardian(constants.childName);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenContainsTheTitle(generalPage.whoLookAfterYourChilderenTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.addPrimaryGuardian();
                await generalStep.createAndAssignContact(constants.primaryParentData, constants.guardianType);
                await generalStep.verifyWithButtonScreenTitleIsVisible(generalPage.continueTxt);
                /** this is a bug, uncomment the code after issue get resolved */
                // await generalStep.addBackUpGuardian();
                // await generalStep.createAndAssignContact(constants.backupParentData, "");
                await generalStep.verifyWithButtonScreenTitleIsVisible(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldYouLikeNameConservatorChild);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWouldYouLiketoNameAsConservator);
                await generalStep.clickOnAddConservatorButton();
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryParentData.firstName} ${constants.primaryParentData.lastName}`, constants.guardianType);
                await generalStep.clickOnAddContactButtonByIndex(constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.futureAdoptionChildrenWillTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.testLivingTrustTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.inputByLabel(generalPage.nameOfYourTrustTxt, constants.silverOakTrust);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whenWouldYouBeginTrust);
                await generalStep.verifyTrustDatePickerPrepopulated();
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldYouMainPersonToManageTrustTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.areYouAsGrantorTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldYouMainPersonToManageTrustTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWouldBeTrusteeTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.verifyButtonIsDisabled(generalPage.confirmTxt);
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryParentData.firstName} ${constants.primaryParentData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.areYouAsGrantorTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoShouldTrusteeIncapacitatedTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.areYouAsGrantorTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wholWillLifetimeBeneficiaryTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt)
                await generalStep.createAndAssignContact(constants.executorData, constants.guardianType)
                await generalStep.clickOnContinueButton()
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoShouldTrusteeIncapacitatedTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.createAndAssignContact(constants.monitorData, constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWouldTakeOverPassAwayTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.createAndAssignContact(constants.successorData, constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doYouHavePetTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.weAreGoingAssetSectionTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doYouHavePetTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doYouWantChoosePetGuardianTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.weAreGoingAssetSectionTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doYouWantChoosePetGuardianTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.listOfPetsDescTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnAddPetByIndex(1);
                await generalStep.fillInputByLabel(generalPage.petsNameLabel, constants.petName, "");
                await generalStep.clickOnAddPetByIndex(2);
                await generalStep.clickOnButtonByXpath(generalPage.editPetXpath);
                await generalStep.fillInputByLabel(generalPage.petsNameLabel, constants.dogBella, "");
                await generalStep.clickOnAddPetByIndex(1);
                await generalStep.clickOnButtonByXpath(generalPage.deletePetXpath);
                await generalStep.clickOnAddPetByIndex(1);
                await generalStep.fillInputByLabel(generalPage.petsNameLabel, constants.petName, "");
                await generalStep.clickOnAddPetByIndex(2);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyPetGuardianAssignmentScreenIsVisible(constants.petName);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.addPrimaryGuardian();
                await generalStep.createAndAssignContact(constants.primaryPetGuardianData, constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.setAsideMoenyToCaringPersonHelp);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.weAreGoingAssetSectionTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.setAsideMoenyToCaringPersonHelp);
                await generalStep.clickYesRadioButton();
                await generalStep.inputByLabel(generalPage.amountLabel, constants.inValidCaringPersonAmount);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.caringPersonAmountError);
                await generalStep.inputByLabel(generalPage.amountLabel, constants.caringPersonAmount);
                await generalStep.clickOnContinueButton();
            });
        },
        async individualTrustUserNegativeBasicAddressToConservatorSetup(constants) {
            await allure.step("Verify system blocks progression and shows proper validation messages when required fields, address details, contact details, trustee details, guardian details, and funding inputs are invalid or incomplete.", async () => {
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.enterAddressLine1(constants.addressLine1);
                await generalStep.enterAddressLine2(constants.addressLine2);
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.enterCity(constants.city);
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.enterZipCode(constants.invalidZipCode);
                await generalStep.selectItemFromDropDown(constants.enterCountery, constants.selectCountryFromDropdown);
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.selectItemFromDropDown(constants.enterState, constants.selectStateFromDropdown);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.zipcodeFormatError);
                await generalStep.enterZipCode(constants.zipcode);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whatisYourbirthdayTxt);
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.enterBirthDayDate(constants.invalidBirthdayDate);
                await page.keyboard.press(generalPage.enterTxt)
                await generalStep.verifyErrorIsVisible(generalPage.fieldRequiredError);
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.enterBirthDayDate(constants.birthdayDate);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyDoyouHavChildrenScreenIsVisible();
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.gatherInfoAboutChilderenTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickAddAChildAndItsDetailsWithValidations(constants.adultChildName, constants.invalidAdultChildDOB);
                await generalStep.clickAddAChildAndItsDetails(constants.childName);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.guardianNominationTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.futureAdoptionChildrenWillTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.testLivingTrustTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyButtonIsDisabled(generalPage.continueTxt);
                await generalStep.inputByLabel(generalPage.nameOfYourTrustTxt, constants.silverOakTrust);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whenWouldYouBeginTrust);
                await generalStep.verifyTrustDatePickerPrepopulated();
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldYouMainPersonToManageTrustTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWouldBeTrusteeTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.verifyButtonIsDisabled(generalPage.confirmTxt);
                await generalStep.createValidateAndAssignContact(constants.trusteeData);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.areYouAsGrantorTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wholWillLifetimeBeneficiaryTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt)
                await generalStep.createAndAssignContact(constants.executorData, constants.guardianType)
                await generalStep.clickOnContinueButton()
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoShouldTrusteeIncapacitatedTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.createAndAssignContact(constants.monitorData, constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWouldTakeOverPassAwayTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.createAndAssignContact(constants.successorData, constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doYouHavePetTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doYouWantChoosePetGuardianTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.listOfPetsDescTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnAddPetByIndex(1);
                await generalStep.clickOnAddPetByIndex(2);
                await generalStep.verifyErrorIsVisible(generalPage.petNameRequiredError);
                await generalStep.fillInputByLabel(generalPage.petsNameLabel, "   ", "");
                await generalStep.verifyErrorIsVisible(generalPage.petNameRequiredError);
                await generalStep.fillInputByLabel(generalPage.petsNameLabel, constants.petName, "");
                await generalStep.clickOnAddPetByIndex(2);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyPetGuardianAssignmentScreenIsVisible(constants.petName);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.addPrimaryGuardian();
                await generalStep.createAndAssignContact(constants.primaryPetGuardianData, constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.setAsideMoenyToCaringPersonHelp);
                await generalStep.clickYesRadioButton();
                await generalStep.inputByLabel(generalPage.amountLabel, constants.inValidCaringPersonAmount);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.caringPersonAmountError);
                await generalStep.inputByLabel(generalPage.amountLabel, constants.assetsTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.caringPersonAmountError);
                await generalStep.inputByLabel(generalPage.amountLabel, constants.caringPersonAmount);
                await generalStep.clickOnContinueButton();
            });
        },
        async individualTrustUserAssetSetup(constants) {
            await allure.step("Ensure user can successfully complete entire Assets flow from Intro screen to Backup Residuary with all conditional scenarios (YES/NO), validations, Add/Edit/Delete, distribution types", async () => {
                await generalStep.verifyWithHeadingScreenContainsTheTitle(generalPage.whatisValueOfAssetsTxt);
                await generalStep.clickRadioButtonByText(generalPage.valueOfAllAsset);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doyouHaveAnyPropertyTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.currentAddressPropTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.provideDetailOfPropertyTxt);
                await generalStep.clickOnAddPropertyButton();
                await generalStep.addPropertyDataWithValidations(constants.propertyData);
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, `${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, "");
                await generalStep.clickOnButtonByText(generalPage.addPersonTxt + " " + generalPage.addPersonTxt);
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, constants.adultChildName, "", 1);
                await generalStep.fillInputByLabel(generalPage.distrubutionTxt, constants.thirty);
                await generalStep.clickOnSaveButton();
                // await generalStep.verifyErrorIsVisible(generalPage.distributionError);
                await generalStep.fillInputByLabel(generalPage.distrubutionTxt, constants.fifty);
                await generalStep.clickOnSaveButton();
                await generalStep.clickOnButtonByXpath(generalPage.editPetXpath);
                await generalStep.fillInputByLabel(generalPage.addressLine2Property, constants.primaryPetGuardianData.addressLine2, constants.guardianType);
                await generalStep.clickOnButtonByText(generalPage.updatePropertyTxt);
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, `${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, "");
                await generalStep.clickOnSaveButton();
                await generalStep.clickOnButtonByXpath(generalPage.deletePetXpath);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.currentAddressPropTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doyouHaveAnyPropertyTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doyouHaveFinancialAccountTxt);
                await generalStep.clickYesRadioButton()
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.pleaseProvideAccountDetailTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.addAccountTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.financialInstitutionRequiredError);
                await generalStep.fillInputByLabel(generalPage.financialInstitutionLabel, constants.financialInstitution, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.selectAtleastOneTypeError);
                await generalStep.fillInputByLabel(generalPage.approxmateAccountValue, constants.approximateAccountValue, "");
                await generalStep.clickRadioButtonByText(generalPage.radioButtonChecking);
                await generalStep.clickOnContinueButton();
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, `${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, "");
                await generalStep.clickOnButtonByText(generalPage.addPersonTxt + " " + generalPage.addPersonTxt);
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, constants.adultChildName, "", 1);
                await generalStep.fillInputByLabel(generalPage.distrubutionTxt, constants.thirty);
                await generalStep.clickOnSaveButton();
                await generalStep.verifyErrorIsVisible(generalPage.distributionError);
                await generalStep.fillInputByLabel(generalPage.distrubutionTxt, constants.fifty);
                await generalStep.clickOnSaveButton();
                await generalStep.clickOnButtonByXpath(generalPage.editPetXpath);
                await generalStep.clickRadioButtonByText(generalPage.savingsTxt)
                await generalStep.clickOnContinueButton(1);
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, `${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, "");
                await generalStep.clickOnSaveButton();
                await generalStep.clickOnButtonByXpath(generalPage.deletePetXpath);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doyouHaveFinancialAccountTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doyouHaveLifeInsuranceTxt);
                await generalStep.clickYesRadioButton()
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.pleaseProvideDetailsLifeInsuTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.addPolicyTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.policyCarrierError);
                await generalStep.verifyErrorIsVisible(generalPage.policyTypeError);
                await generalStep.fillInputByLabel(generalPage.policyCarrierTxt, constants.policyCarrier, "");
                await generalStep.selectItemFromDropDown(constants.policyType.substring(0, 6), constants.policyType);
                await generalStep.clickOnContinueButton();
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, `${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, "");
                await generalStep.clickOnButtonByText(generalPage.addPersonTxt + " " + generalPage.addPersonTxt);
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, constants.adultChildName, "", 1);
                await generalStep.fillInputByLabel(generalPage.distrubutionTxt, constants.thirty);
                await generalStep.clickOnSaveButton();
                await generalStep.verifyErrorIsVisible(generalPage.distributionError);
                await generalStep.fillInputByLabel(generalPage.distrubutionTxt, constants.fifty);
                await generalStep.clickOnSaveButton();
                await generalStep.clickOnButtonByXpath(generalPage.editPetXpath);
                await generalStep.selectItemFromDropDown(constants.policyType.substring(0, 6), constants.policyType);
                await generalStep.clickOnContinueButton(1);
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, `${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, "");
                await generalStep.clickOnSaveButton();
                await generalStep.clickOnButtonByXpath(generalPage.deletePetXpath);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doyouHaveLifeInsuranceTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doyouHaveBusinessIntrestTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.pleaseProvideBusessIntrestTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.addIntrestTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.businessNameError);
                await generalStep.verifyErrorIsVisible(generalPage.businessTypeError);
                await generalStep.fillInputByLabel(generalPage.businessNameLabel, constants.businessName, "");
                await generalStep.selectItemFromDropDown(constants.businessType.substring(0, 6), constants.businessType);
                await generalStep.selectItemFromDropDown(generalPage.ownerTxt.substring(0, 3), generalPage.ownerTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, `${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, "");
                await generalStep.clickOnSaveButton();
                await generalStep.clickOnButtonByXpath(generalPage.editPetXpath);
                await generalStep.fillInputByLabel(generalPage.businessNameLabel, constants.summitEnterPrisesBusiName, "");
                await generalStep.clickOnContinueButton(1);
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, `${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, "");
                await generalStep.clickOnSaveButton();
                await generalStep.clickOnButtonByXpath(generalPage.deletePetXpath);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.doyouHaveBusinessIntrestTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.dyouHaveItemsTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.provideDetailsAboutItemsTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.addItemTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.itemNameError);
                await generalStep.verifyErrorIsVisible(generalPage.itemDescError);
                await generalStep.fillInputByLabel(generalPage.itemNameLabel, constants.itemData.name, "");
                await generalStep.fillInputByLabel(generalPage.briefDescriptionLabel, constants.itemData.description, "");
                await generalStep.fillInputByLabel(generalPage.estimateValueLabel, constants.itemData.estimatedValue, "");
                await generalStep.clickOnContinueButton();
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, `${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, "");
                await generalStep.clickOnButtonByText(generalPage.addPersonTxt + " " + generalPage.addPersonTxt);
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, constants.adultChildName, "", 1);
                await generalStep.fillInputByLabel(generalPage.distrubutionTxt, constants.thirty);
                await generalStep.clickOnSaveButton();
                await generalStep.verifyErrorIsVisible(generalPage.distributionError);
                await generalStep.fillInputByLabel(generalPage.distrubutionTxt, constants.fifty);
                await generalStep.clickOnSaveButton();
                await generalStep.clickOnButtonByXpath(generalPage.editPetXpath);
                await generalStep.fillInputByLabel(generalPage.itemNameLabel, constants.watchItemData.name, "");
                await generalStep.fillInputByLabel(generalPage.briefDescriptionLabel, constants.watchItemData.description, "");
                await generalStep.clickOnContinueButton(1);
                await generalStep.fillInputByLabelAndSelectFromDropdown(generalPage.fullNameLabel, `${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, "");
                await generalStep.clickOnSaveButton();
                await generalStep.clickOnButtonByXpath(generalPage.deletePetXpath);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.dyouHaveItemsTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.howToDistributePersonalPropertyTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.pleaseSelectAtleastOneOptionError);
                await generalStep.clickRadioButtonByText(generalPage.childrenTxt);
                await generalStep.clickOnButtonByText(generalPage.addPersonTxt);
                await generalStep.inputByPlaceholder(generalPage.spouseInputPlaceHolder, constants.iName);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.howToDivideTangibleProprtyTxt);
                await generalStep.clickRadioButtonByText(generalPage.customePercentageTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.totalShould100PercentError)
                await generalStep.verifyErrorIsVisible(generalPage.enterPercEachBenefError);
                await generalStep.inputByXpath(generalPage.benefePercentageXpath(constants.adultChildName), constants.thirty);
                await generalStep.inputByXpath(generalPage.benefePercentageXpath(constants.iName), constants.twenty);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.totalShould100PercentError)
                await generalStep.inputByXpath(generalPage.benefePercentageXpath(constants.childName), constants.fifty);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.beneficairyReceiveInheritanceTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.howLongbeneficliveAfterPasstoInheritTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.numberOfSurvivorshipError);
                await generalStep.fillInputByLabel(generalPage.numberOfDaysLabel, constants.minusThirty, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.numberShouldBtwError);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.beneficairyReceiveInheritanceTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whatAgeBeneReceiveAssetsTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.ageDistributionError);
                await generalStep.inputByPlaceholder(generalPage.agePlaceHolderTxt, constants.minusThirty)
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.ageShouldBtwBeError);
                await generalStep.inputByPlaceholder(generalPage.agePlaceHolderTxt, constants.twentyFive);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldBeneficHavRightEarlyWithdrawTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.beneficBeAbleToWithdrawTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.ageForWithdrawalError);
                await generalStep.verifyErrorIsVisible(generalPage.withdrawalLevelError);
                await generalStep.fillInputByLabel(generalPage.firstAgeOfBenefTxt, constants.minusThirty, "");
                await generalStep.fillInputByLabel(generalPage.firstWithdrawalPercentageTxt, constants.minusThirty, "");
                await generalStep.fillInputByLabel(generalPage.secondAgeOfBenefTxt, constants.minusThirty, "");
                await generalStep.fillInputByLabel(generalPage.secondWithdrawalPercentageTxt, constants.minusThirty, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.withdrawTrustAgeMustBeZeroError);
                await generalStep.verifyErrorIsVisible(generalPage.withdrawL1PercentageBtwError);
                await generalStep.verifyErrorIsVisible(generalPage.withdrawL2PercentageBtwError);
                await generalStep.fillInputByLabel(generalPage.firstAgeOfBenefTxt, constants.thirty, "");
                await generalStep.verifyErrorIsVisible(generalPage.mustBeLessAgeOfDistruError);
                /** test is blocked due unable to move to next screen */
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.howyouLikeResiduaryDistrubutedTxt);
                await generalStep.clickRadioButtonByText(generalPage.childrenTxt);
                await generalStep.clickOnButtonByText(generalPage.addPersonTxt);
                await generalStep.inputByPlaceholder(generalPage.spouseInputPlaceHolder, constants.iName);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantToSplitResiduaryTxt);
                await generalStep.clickRadioButtonByText(generalPage.customePercentageTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIncludeIsVisible(generalPage.percentagesMustBe100PercentageError);
                await generalStep.inputByXpath(generalPage.benefePercentageXpath(constants.adultChildName), constants.thirty);
                await generalStep.inputByXpath(generalPage.benefePercentageXpath(constants.iName), constants.twenty);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIncludeIsVisible(generalPage.percentagesMustBe100PercentageError);
                await generalStep.inputByXpath(generalPage.benefePercentageXpath(constants.childName), constants.fifty);
                await generalStep.clickRadioButtonByText(generalPage.divideEvenlyTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.backupResiduaryDistributedTxt);
                await generalStep.clickRadioButtonByText(generalPage.myDecendentsTxt);
                await generalStep.clickRadioButtonByText(generalPage.perRepresentationTxt);
                await generalStep.clickRadioButtonByText(generalPage.perStirpesTxt);
                await generalStep.clickRadioButtonByText(generalPage.perCapitaTxt);
                await generalStep.clickOnContinueButton();
            })
        },
        async individualTrustUserArrangmentSetup(constants) {
            await allure.step("Verify complete Arrangements section end-to-end including Conservator contact modal actions (Create, Select, Edit, Delete, See More) and all conditional flows", async () => {
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWillbeExecutorTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantBackupExecutor);
                await generalStep.clickYesRadioButton();
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.shouldExecutorRequiredBond);
                await generalStep.clickYesRadioButton();
                await generalStep.fillInputByLabel(generalPage.howMuchForBondTxt, constants.hundredThousand, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantToMonitorTxt)
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWouldLikeNameasMonitorTxt)
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt)
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantNameConservatorEstateTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.createAndAssignContact(constants.backupExecutorData, constants.guardianType)
                await generalStep.clickOnContinueButton()
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.nominateBackupEstateConserTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.conservatorBondTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantNominateGuardianForSelfTxt)
                await generalStep.clickYesRadioButton();
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantExludeFromWill);
                await generalStep.clickYesRadioButton()
                await generalStep.fillInputByLabel(generalPage.nameOfPersonOrOrganizationLabel, constants.policyHolderName, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.finalRestingPlaceTxt);
                await generalStep.clickRadioButtonByText(generalPage.cremationTxt)
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.cremonyTypeTxt);
                await generalStep.clickRadioButtonByText(generalPage.memorialServiceTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.haveSpecialRequestforCremony);
                await generalStep.clickYesRadioButton();
                await generalStep.fillInTextAreaByLabel(generalPage.myRequestLabel, constants.cremondyRequest, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldYouLikeProtectWillFromPotentialDesputeTxt)
                await generalStep.clickYesRadioButton();
            });
        },
        async individualTrustNegativeUserArrangmentSetup(constants) {
            await allure.step("Verify Arrangement section validation behavior, disabled states, contact modal validations, and conditional dependency handling", async () => {
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWillbeExecutorTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.verifyWithButtonScreenTitleIsVisible(generalPage.continueTxt);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantBackupExecutor);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWillbeBackupExecutorTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.verifyWithButtonScreenTitleIsVisible(generalPage.continueTxt);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.shouldExecutorRequiredBond);
                await generalStep.clickYesRadioButton();
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.bondAmounError);
                await generalStep.fillInputByLabel(generalPage.howMuchForBondTxt, constants.minusThirty, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.invalidBondAmountError);
                await generalStep.fillInputByLabel(generalPage.howMuchForBondTxt, constants.hundredThousand, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantToMonitorTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWouldLikeNameasMonitorTxt);
                await generalStep.verifyButtonIsNotVisible(generalPage.continueTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.verifyButtonIsDisabled(generalPage.confirmTxt);
                await generalStep.createValidateAndAssignContact(constants.monitorData);
                await generalStep.verifyWithButtonScreenTitleIsVisible(generalPage.continueTxt);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();                
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantNameConservatorEstateTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.verifyButtonIsDisabled(generalPage.confirmTxt);
                await generalStep.createValidateAndAssignContact(constants.backupExecutorData, constants.guardianType);
                await generalStep.verifyWithButtonScreenTitleIsVisible(generalPage.continueTxt);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnButtonByXpath(generalPage.editPetXpath);
                await generalStep.clickOnButtonByXpath(generalPage.showMoreButtonXpath(`${constants.backupExecutorData.firstName} ${constants.backupExecutorData.lastName}`));
                await generalStep.clickOnButtonByXpath(generalPage.editContactButtonXpath(`${constants.backupExecutorData.firstName} ${constants.backupExecutorData.lastName}`));
                await generalStep.clearInputByLabel(generalPage.firstName, constants.guardianType);
                await generalStep.clearInputByLabel(generalPage.lastName, constants.guardianType);
                await generalStep.clearInputByLabel(generalPage.email, constants.guardianType);
                await generalStep.clearInputByLabel(generalPage.zipCode, constants.guardianType);
                await generalStep.clearInputByLabel(generalPage.phone, constants.guardianType);
                await generalStep.clearInputByLabel(generalPage.city, constants.guardianType);
                await generalStep.clearInputByLabel(generalPage.addressLine1, constants.guardianType);                
                await generalStep.clickOnAddContactButtonByIndex(constants.guardianType);
                await generalStep.verifyErrorIsVisible(generalPage.firstNameRequiredError);
                await generalStep.verifyErrorIsVisible(generalPage.lastNameRequiredError);
                await generalStep.verifyErrorIsVisible(generalPage.emailRequiredError);
                await generalStep.verifyErrorIsVisible(generalPage.phoneNumberRequiredError);
                await generalStep.verifyErrorIsVisible(generalPage.addressLCapLine1RequiredError);
                await generalStep.verifyErrorIsVisible(generalPage.cityRequiredError);
                await generalStep.verifyErrorIsVisible(generalPage.zipCodeRequiredError);
                await generalStep.clickOnButtonByText(generalPage.cancelTxt)
                await generalStep.clickOnButtonByXpath(generalPage.deletePetXpath);
                await generalStep.verifyWithButtonScreenTitleIsVisible(generalPage.selectContactTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.backupExecutorData.firstName} ${constants.backupExecutorData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.nominateBackupEstateConserTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.backupConservatorError);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.backupExecutorData.firstName} ${constants.backupExecutorData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.conservatorBondTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantNominateGuardianForSelfTxt)
                await generalStep.clickYesRadioButton();
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.guardianError);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt);
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.backupExecutorData.firstName} ${constants.backupExecutorData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantExludeFromWill);
                await generalStep.clickYesRadioButton();
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.disinheritanceError);
                await generalStep.fillInputByLabel(generalPage.nameOfPersonOrOrganizationLabel, constants.policyHolderName, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.finalRestingPlaceTxt);
                await generalStep.clickRadioButtonByText(generalPage.cremationTxt)
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.cremonyTypeTxt);
                await generalStep.clickRadioButtonByText(generalPage.memorialServiceTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.haveSpecialRequestforCremony);
                await generalStep.clickYesRadioButton();
                await generalStep.clickOnContinueButton();
                await generalStep.verifyErrorIsVisible(generalPage.specialRequestDetailError);
                await generalStep.fillInTextAreaByLabel(generalPage.myRequestLabel, constants.cremondyRequest, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldYouLikeProtectWillFromPotentialDesputeTxt)
                await generalStep.clickYesRadioButton();


                // remainging steps
            });
        },
        async individualWillUserHealthCareSetup(constants) {
            await allure.step("Verify user can complete full Healthcare section including primary agent, backup agent, instructions, permissions, limits, organ donation, authorization, expiration, branching logic, validations, and navigation", async () => {
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWillMakeMedicalDecision);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt)
                await generalStep.createAndAssignContact(constants.healthCareAgentData, constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantNameBackupHealthAgentTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWillBackupAgentTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt)
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWillBackupAgentTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantNameBackupHealthAgentTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.leaveMedicalCarforAgentTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.clickRadioButtonByText(generalPage.alwaysReceiveCareTxt);
                await generalStep.verifyWithHeadingScreenContainsTheTitle(generalPage.beAbleToHelpWithTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.leaveMedicalCarforAgentTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenContainsTheTitle(generalPage.beAbleToHelpWithTxt);
                await generalStep.verifyWithTextScreenIsVisible(generalPage.selectTaskYounWantYourHealthCarAgentManageTxt);
                await generalStep.clickSwitchButtonByText(generalPage.hipaaAuthorizationTxt);
                await generalStep.clickSwitchButtonByText(generalPage.guardianTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.anyLimitForHealthTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.fillInTextAreaByLabel(generalPage.yourMedicalCareInstructionsTxt, constants.medicalInstrumentDetailTxt, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantDonateOrganTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.anyLimitForHealthTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantDonateOrganTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.clickRadioButtonByText(generalPage.followOrgansEyesAndTissuesTxt);
                await generalStep.fillInTextAreaByLabel(generalPage.typeInstuctionHereTxt, constants.organsInstructionTxt, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldLikeGivePermissionViewMedicalRecordsTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantDonateOrganTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldLikeGivePermissionViewMedicalRecordsTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt)
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.primaryPetGuardianData.firstName} ${constants.primaryPetGuardianData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantWhenHealthProxyNoLongerEffectTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldLikeGivePermissionViewMedicalRecordsTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantWhenHealthProxyNoLongerEffectTxt);
                await generalStep.clickRadioButtonByText(generalPage.yesIwouldLikeToChooseTxt);
                await generalStep.fillInputByLabel(generalPage.thisProxyShallExpireLabel, constants.healthCareProxyExpiryMessage, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.financialCareSectionTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantWhenHealthProxyNoLongerEffectTxt);
                await generalStep.clickRadioButtonByText(generalPage.noEndMyRequestTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.financialCareSectionTxt);
            });
        },
        async individualWillNegativeUserHealthCareSetup(constants) {
            await allure.step("Verify system prevents user from progressing in Healthcare section when required inputs are missing, invalid, or incomplete", async () => {
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWillMakeMedicalDecision);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt)
                await generalStep.createAndAssignContact(constants.healthCareAgentData, constants.guardianType);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantNameBackupHealthAgentTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWillBackupAgentTxt);
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt)
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.healthCareAgentData.firstName} ${constants.healthCareAgentData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.whoWillBackupAgentTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantNameBackupHealthAgentTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.leaveMedicalCarforAgentTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.clickRadioButtonByText(generalPage.alwaysReceiveCareTxt);
                await generalStep.verifyWithHeadingScreenContainsTheTitle(generalPage.beAbleToHelpWithTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.leaveMedicalCarforAgentTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenContainsTheTitle(generalPage.beAbleToHelpWithTxt);
                await generalStep.verifyWithTextScreenIsVisible(generalPage.selectTaskYounWantYourHealthCarAgentManageTxt);
                await generalStep.clickSwitchButtonByText(generalPage.hipaaAuthorizationTxt);
                await generalStep.clickSwitchButtonByText(generalPage.guardianTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.anyLimitForHealthTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.fillInTextAreaByLabel(generalPage.yourMedicalCareInstructionsTxt, constants.medicalInstrumentDetailTxt, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantDonateOrganTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.anyLimitForHealthTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantDonateOrganTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.clickRadioButtonByText(generalPage.followOrgansEyesAndTissuesTxt);
                await generalStep.fillInTextAreaByLabel(generalPage.typeInstuctionHereTxt, constants.organsInstructionTxt, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldLikeGivePermissionViewMedicalRecordsTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantDonateOrganTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldLikeGivePermissionViewMedicalRecordsTxt);
                await generalStep.clickYesRadioButton();
                await generalStep.clickOnButtonByText(generalPage.selectContactTxt)
                await generalStep.clickGuardianToAssignToChildByIndex(`${constants.healthCareAgentData.firstName} ${constants.healthCareAgentData.lastName}`, constants.guardianType);
                await generalStep.verifyButtonIsEnabled(generalPage.confirmTxt);
                await generalStep.clickOnButtonByText(generalPage.confirmTxt);
                await generalStep.verifyButtonIsEnabled(generalPage.continueTxt);
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantWhenHealthProxyNoLongerEffectTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wouldLikeGivePermissionViewMedicalRecordsTxt);
                await generalStep.clickRadioButtonByText(generalPage.noTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantWhenHealthProxyNoLongerEffectTxt);
                await generalStep.clickRadioButtonByText(generalPage.yesIwouldLikeToChooseTxt);
                await generalStep.fillInputByLabel(generalPage.thisProxyShallExpireLabel, constants.healthCareProxyExpiryMessage, "");
                await generalStep.clickOnContinueButton();
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.financialCareSectionTxt);
                await generalStep.clickOnButtonByText(generalPage.backTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.wantWhenHealthProxyNoLongerEffectTxt);
                await generalStep.clickRadioButtonByText(generalPage.noEndMyRequestTxt);
                await generalStep.verifyWithHeadingScreenIsVisible(generalPage.financialCareSectionTxt);
            });
        },
    }

}